### ISSUE TITLE
Controlling processes

### ISSUE THREAD

**Issue by MichaelLiss** [osquery/osquery#5815] opened 2019-09-18 17:35 UTC
Hi,

I have read the documents on OS Query, and it seems to me that OS Query is a "read only" proposition.  Meaning, I can only read information about the system, and not control certain apsects of the system via OS Query. 

In other words, let say I want to know when "John Smith" logs in on Machine "ABC".  I'm pretty sure I can use OS Query to find when that occurs.  However, let's me expand my scenario a bit.  When he logs on that particular machine, he plays solitare.   I want to stop "solitare" from running when John logs onto machine ABC - as he spends inordinate amounts of time playing it.  

So my question : Can OS Query prevent a process, for a particular user, on a particular machine from running?

Thanks

**Comment by groob** [comment] 2019-09-18 17:56
Osquery cannot. It is read-only and will always be this way as a core project. 

But osquery is extensible. You can write an extension which can do what you want. 
You can also use a tool that is not osquery to perform remediation. 

Examples of extensions and SDKs:
https://github.com/trailofbits/osquery-extensions (C++)
https://github.com/kolide/osquery-go (Go)
https://github.com/osquery/osquery-python

Using any of the above SDK it is possible to implement something like:

`SELECT pid from processes JOIN my_custom_table USING pid where name = 'solitare' and my_custom_table.action = terminate`.

**Comment by directionless** [comment] 2019-09-18 18:06
In addition to the an action, you could look at writable tables. Those won't be in core, but it's another model you can use in extensions. See https://blog.trailofbits.com/2018/05/30/manage-your-fleets-firewalls-with-osquery/ for some background

**Comment by MichaelLiss** [comment] 2019-09-18 18:14
https://github.com/directionless - Where is some information on creating writable tables and how they are integrated into OS Query solutions?

**Comment by directionless** [comment] 2019-09-18 19:30
The ones I've seen are linked from the blog post in my prior comment

**Comment by groob** [comment] 2019-09-18 19:34
I'm closing the issue because it is not a bug and the discussion so far has sufficiently answered it. 
(This is a great stackoverflow or slack question but is otherwise not actionable here).

**Closed by groob** 2019-09-18 19:34 UTC
Labels: question
