### ISSUE TITLE
Restarting sssd while running osqueryd causes system crash

### ISSUE THREAD

**Issue by bpruce** [osquery/osquery#4794] opened 2018-08-02 12:24 UTC
### What version of `osquery` are you using? What operating system. Be specific.
System Details:
-----------
root@<hostname>:~ # uname -a
Linux <hostname>4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

root@<hostname>:~ # dpkg -s osquery
Package: osquery
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 23521
Maintainer: osquery@osquery.io
Architecture: amd64
Version: 3.2.6-1.linux
Depends: libc6 (>= 2.12), zlib1g
Conffiles:
 /etc/default/osqueryd 1c48f2333fda8ccb186257ae22716520
 /etc/init.d/osqueryd 8d2138e9254a3c4d730632cfa1212160
Description: osquery is an operating system instrumentation toolchain.
License: BSD
Vendor: Facebook
Homepage: https://osquery.io

root@<hostname>:~ # dpkg -s sssd   
Package: sssd
Status: install ok installed
Priority: extra
Section: metapackages
Installed-Size: 44
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.11.8-0ubuntu0.7
Depends: sssd-common (= 1.11.8-0ubuntu0.7), sssd-ad (= 1.11.8-0ubuntu0.7), sssd-ipa (= 1.11.8-0ubuntu0.7), sssd-krb5 (= 1.11.8-0ubuntu0.7), sssd-ldap (= 1.11.8-0ubuntu0.7), sssd-proxy (= 1.11.8-0ubuntu0.7), python-sss (= 1.11.8-0ubuntu0.7)
Description: System Security Services Daemon -- metapackage
 Provides a set of daemons to manage access to remote directories and
 authentication mechanisms. It provides an NSS and PAM interface toward
 the system and a pluggable backend system to connect to multiple different
 account sources. It is also the basis to provide client auditing and policy
 services for projects like FreeIPA.
 .
 This package is a metapackage which installs the daemon and existing
 authentication back ends.
Homepage: https://fedorahosted.org/sssd/
Original-Maintainer: Debian SSSD Team <pkg-sssd-devel@lists.alioth.debian.org>

root@<hostname>:~ # cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

### What have you already tried?
Sssd is in use for ldap authentication.  We recently needed to make config changes and when restarting the sssd on ubuntu14 vm's the entire OS crashes. This has occurred on about 10 systems now, 9 of which required resetting the VM. We did find that stopping the osqueryd first and then restarting the sssd does not have the same issue. In fact, you can ssh into a server, restart sssd and it will crash if osqueryd is running. No config changes required. 

### What did you expect to see?
restarting sssd not crashing the host when osquery is running

### What did you see instead?
OS crash if osqueryd running and restarting sssd.

**Comment by uptycs-nishant** [comment] 2018-08-02 13:40
@bpruce , What message do you see in you syslog/ kern.log regarding this crash?

**Comment by bpruce** [comment] 2018-08-22 14:54
The entire OS just hangs.  DiskIO stops.  Can't ping it.   Nothing on the console but a login prompt that doesn't respond.  There's really nothing in syslog/kern.log that's helpful unfortunately.  It just stops functioning and then you see the boot data shortly after. 

`<46>1 2018-08-01T23:41:02.391623-03:00  rsyslogd - - - rsyslogd's groupid changed to 104
<46>1 2018-08-01T23:41:02.391842-03:00  rsyslogd - - - rsyslogd's userid changed to 101
<6>1 2018-08-01T23:41:02.392073-03:00  kernel - - - [    0.000000] Initializing cgroup subsys cpuset
<6>1 2018-08-01T23:41:02.392295-03:00  kernel - - - [    0.000000] Initializing cgroup subsys cpu
<6>1 2018-08-01T23:41:02.392296-03:00  kernel - - - [    0.000000] Initializing cgroup subsys cpuacct
<5>1 2018-08-01T23:41:02.392299-03:00  kernel - - - [    0.000000] Linux version 4.4.0-116-generic (buildd@lcy01-amd64-023) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4) ) #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 (Ubuntu 4.4.0-116.140~14.04.1-generic 4.4.98)
<`

Same with kern.log 
`<5>1 2018-08-01T16:34:01.126878-03:00  kernel - - - [7700849.196893] audit: type=1305 audit(1533152041.110:9320834): auid=4294967295 ses=4294967295 op="remove_rule" key=(null) list=4 res=0
<6>1 2018-08-01T23:41:02.392073-03:00  - - - [    0.000000] Initializing cgroup subsys cpuset
<6>1 2018-08-01T23:41:02.392295-03:00  kernel - - - [    0.000000] Initializing cgroup subsys cpu
<`

**Comment by Smjert** [comment] 2020-12-22 12:54
@bpruce I'm going to close this issue since a lot of time has passed and osquery changed a quite a bit since then.
I find it a bit strange that osquery would cause such interactions with the system, but if this is still happening, we would need a minimum reproducible example. It would be useful to have both the osquery configuration and an idea of the sssd configuration.

**Closed by Smjert** 2020-12-22 12:54 UTC
