### ISSUE TITLE
Osquery with ELK integration

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6926] opened 2021-01-27 11:51 UTC
I have deployed the Osquery in 10 virtual machines and deployed the ELK in one main machine. Now i am trying to getting the osquery data from those 10 virtual machines into one main machine where ELK was installed.(logstash-->elastic-->kibana)

When i tried to access the data from main machine it's not reading and not throwing any error. Please  suggest further.

**Comment by directionless** [comment] 2021-01-30 03:02
This issue is a duplicate of #6862. @bhuvaneswari01, please do not open multiple issues for the same question or problem. I also see that you are asking the same questions in Slack, please be patient as people are trying to learn more about your problem and are asking you clarifying questions. Please do not ask the same question in multiple places as it makes it difficult to answer you.

**Closed by directionless** 2021-01-30 03:02 UTC
Labels: question
