### ISSUE TITLE
distributed_plugin=filesystem causing osqueryd to exit 

### ISSUE THREAD

**Issue by teddorosheff** [osquery/osquery#7471] opened 2022-02-01 18:50 UTC
# Bug report

### What operating system and version are you using?

version = 12.0
build = 21A344
platform = darwin

### What version of osquery are you using?

version = 5.1.0

### What steps did you take to reproduce the issue?

in osquery.flags set --distributed_plugin=filesystem

### What did you expect to see?

Before i set the distributed_plugin to filesystem, i saw that the default was TLS. I realized this after i saw the daemon repeatedly trying to post to "http://", no hostname. I intentionally didnt set a tls_hostname because i am testing my config locally and am expecting to see logs posted to /var/log/osquery/osqueryd.results.log, yet i have not seen anything posted there.

```
teddorosheff@DN4FV4WN16 osquery % sudo /opt/osquery/lib/osquery.app/Contents/MacOS/osqueryd --flagfile=osquery.flags --verbose
I0201 13:37:24.258970 114783744 init.cpp:357] osquery initialized [version=5.1.0]
I0201 13:37:24.303323 114783744 system.cpp:348] Found stale process for osqueryd (93797)
I0201 13:37:24.303764 114783744 system.cpp:380] Writing osqueryd pid (94019) to /var/osquery/osqueryd.pidfile
I0201 13:37:24.309437 114783744 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: /var/osquery/extensions.load
I0201 13:37:24.309506 114783744 dispatcher.cpp:78] Adding new service: WatcherRunner (0x6000026a91e8) to thread: 0x30f2e8000 (0x600001bb4ad0) in process 94019
I0201 13:37:24.311878 254705664 watcher.cpp:656] osqueryd watcher (94019) executing worker (94020)
I0201 13:37:24.329511 54773248 init.cpp:354] osquery worker initialized [watcher=94019]
I0201 13:37:24.330155 54773248 dispatcher.cpp:78] Adding new service: WatcherWatcherRunner (0x600001ab4018) to thread: 0x307f56000 (0x6000023b8000) in process 94020
I0201 13:37:24.330626 54773248 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0201 13:37:24.349216 54773248 dispatcher.cpp:78] Adding new service: ExtensionWatcher (0x7fd1a1706a78) to thread: 0x3082eb000 (0x6000023b8310) in process 94020
I0201 13:37:24.349314 54773248 dispatcher.cpp:78] Adding new service: ExtensionRunnerCore (0x7fd1a1708be8) to thread: 0x30836e000 (0x6000023b8030) in process 94020
I0201 13:37:24.349359 54773248 auto_constructed_tables.cpp:97] Removing stale ATC entries
I0201 13:37:24.349433 137814016 interface.cpp:299] Extension manager service starting: /var/osquery/osquery.em
I0201 13:37:27.392527 54773248 aws_util.cpp:445] Request for api/token failed:Failed to connect to 169.254.169.254:80: Operation timed out
I0201 13:37:30.398346 54773248 aws_util.cpp:485] Error checking if this is EC2 instance: Failed to connect to 169.254.169.254:80: Operation timed out
I0201 13:37:30.411711 54773248 eventfactory.cpp:156] Event publisher not enabled: endpointsecurity: EndpointSecurity is disabled via configuration
I0201 13:37:30.413331 54773248 eventfactory.cpp:156] Event publisher not enabled: openbsm: Publisher disabled via configuration
I0201 13:37:30.413367 54773248 eventfactory.cpp:156] Event publisher not enabled: scnetwork: Publisher not used
I0201 13:37:30.413398 54773248 eventfactory.cpp:156] Event publisher not enabled: event_tapping: Publisher disabled via configuration
I0201 13:37:30.414878 54773248 eventsubscriberplugin.cpp:492] Found 20 events for subscriber diskarbitration.disk_events
I0201 13:37:30.416582 54773248 events.cpp:70] Skipping subscriber: socket_events: Subscriber disabled via configuration
I0201 13:37:30.417603 138350592 eventfactory.cpp:390] Starting event publisher run loop: diskarbitration
I0201 13:37:30.417699 138887168 eventfactory.cpp:390] Starting event publisher run loop: fsevents
I0201 13:37:30.417834 139423744 eventfactory.cpp:390] Starting event publisher run loop: iokit
I0201 13:37:30.418345 54773248 dispatcher.cpp:78] Adding new service: DistributedRunner (0x6000014b40d8) to thread: 0x30857a000 (0x6000023b8b90) in process 94020
I0201 13:37:30.418637 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:37:30.419126 54773248 dispatcher.cpp:78] Adding new service: SchedulerRunner (0x6000018a0018) to thread: 0x3085fd000 (0x6000023b8bb0) in process 94020
I0201 13:37:30.419395 141033472 system.cpp:302] Using host identifier: d8f7fa6d-b35f-4eba-b4aa-376f7ab38895
I0201 13:37:31.427415 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:37:35.433543 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:38:35.446249 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:38:36.453615 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:38:40.459967 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:39:40.467393 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:39:41.475479 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
I0201 13:39:45.480697 139960320 tls.cpp:255] TLS/HTTPS POST request to URI: https://
^CI0201 13:39:45.498713 54773248 dispatcher.cpp:149] Thread: 0x20343c600 requesting a stop
```

### What did you see instead?

When i set --distributed_plugin=filesystem (not realizing this isn't even an actual value) and then ran the daemon, it just stops when it gets to that part of the flag file

```
teddorosheff@DN4FV4WN16 osquery % sudo /opt/osquery/lib/osquery.app/Contents/MacOS/osqueryd --flagfile=osquery.flags --verbose
I0201 13:29:22.328708 57648640 init.cpp:357] osquery initialized [version=5.1.0]
I0201 13:29:22.351799 57648640 system.cpp:348] Found stale process for osqueryd (69241)
I0201 13:29:22.351974 57648640 system.cpp:380] Writing osqueryd pid (93797) to /var/osquery/osqueryd.pidfile
I0201 13:29:22.352339 57648640 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: /var/osquery/extensions.load
I0201 13:29:22.352428 57648640 dispatcher.cpp:78] Adding new service: WatcherRunner (0x600001640e28) to thread: 0x308412000 (0x600002b46160) in process 93797
I0201 13:29:22.354625 138485760 watcher.cpp:656] osqueryd watcher (93797) executing worker (93798)
I0201 13:29:22.372586 124622336 init.cpp:354] osquery worker initialized [watcher=93797]
I0201 13:29:22.373185 124622336 dispatcher.cpp:78] Adding new service: WatcherWatcherRunner (0x6000029c4018) to thread: 0x3103d2000 (0x6000010c8000) in process 93798
I0201 13:29:22.373647 124622336 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0201 13:29:22.394670 124622336 dispatcher.cpp:78] Adding new service: ExtensionWatcher (0x7f843d804d18) to thread: 0x310767000 (0x6000010cc0d0) in process 93798
I0201 13:29:22.394743 124622336 dispatcher.cpp:78] Adding new service: ExtensionRunnerCore (0x7f843d804e28) to thread: 0x3107ea000 (0x6000010cc0b0) in process 93798
I0201 13:29:22.394805 124622336 auto_constructed_tables.cpp:97] Removing stale ATC entries
I0201 13:29:22.394814 276733952 interface.cpp:299] Extension manager service starting: /var/osquery/osquery.em
I0201 13:29:25.616849 124622336 aws_util.cpp:445] Request for api/token failed:Failed to connect to 169.254.169.254:80: Operation timed out
I0201 13:29:28.622495 124622336 aws_util.cpp:485] Error checking if this is EC2 instance: Failed to connect to 169.254.169.254:80: Operation timed out
E0201 13:29:28.636067 124622336 shutdown.cpp:79] Cannot activate filesystem distributed plugin: Unknown registry plugin: filesystem
I0201 13:29:28.641175 124622336 dispatcher.cpp:149] Thread: 0x2076d9600 requesting a stop
I0201 13:29:28.641256 124622336 dispatcher.cpp:156] Service: 0x6000029c4018 has been interrupted
I0201 13:29:28.641290 124622336 dispatcher.cpp:156] Service: 0x7f843d804d18 has been interrupted
I0201 13:29:28.641371 124622336 dispatcher.cpp:156] Service: 0x7f843d804e28 has been interrupted
I0201 13:29:28.641404 124622336 dispatcher.cpp:122] Thread: 0x2076d9600 requesting a join
I0201 13:29:28.645545 124622336 dispatcher.cpp:140] Service thread: 0x6000010cc0b0 has joined
I0201 13:29:28.645606 124622336 dispatcher.cpp:140] Service thread: 0x6000010cc0d0 has joined
I0201 13:29:28.645637 124622336 dispatcher.cpp:140] Service thread: 0x6000010c8000 has joined
I0201 13:29:28.645658 124622336 dispatcher.cpp:144] Services and threads have been cleared
E0201 13:29:31.370239 138485760 shutdown.cpp:79] Worker returned exit status
I0201 13:29:31.372150 57648640 dispatcher.cpp:149] Thread: 0x2036fa600 requesting a stop
I0201 13:29:31.372200 57648640 dispatcher.cpp:122] Thread: 0x2036fa600 requesting a join
I0201 13:29:31.372236 57648640 dispatcher.cpp:140] Service thread: 0x600002b46160 has joined
I0201 13:29:31.372251 57648640 dispatcher.cpp:144] Services and threads have been cleared
```

Perhaps this isn't a bug at all and the shutdown is intentional when invalid flags are set, however i was asked to report this as an issue.

**Comment by Smjert** [comment] 2022-02-02 14:39
@teddorosheff I think I may have misunderstood you, I thought a crash was happening, but here osquery is exiting cleanly due to the incorrect flag.
I wouldn't consider this a bug then, since osquery is logging that that plugin is not know here:
```
E0201 13:29:28.636067 124622336 shutdown.cpp:79] Cannot activate filesystem distributed plugin: Unknown registry plugin: filesystem
```
so this is currently the expected behavior.

**Comment by Smjert** [comment] 2022-02-03 17:50
@teddorosheff I'm going to close this, since it's expected behavior. You can use `--disable_distributed=true` or just not set `--disable_distributed=false`, given that the default is disabled, if you want to avoid having the distributed plugin making TLS connections (also the distributed plugin is meant to let the user run ad-hoc queries via their fleet manager, so it's not meant to output anything; it pulls queries to run, runs them and then the results are written by the logger plugin).

**Closed by Smjert** 2022-02-03 17:50 UTC
