### ISSUE TITLE
OSQuery failed to cmake on windows due to error The source directory "OSQuery/" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by dasarinarednra12345** [osquery/osquery#5602] opened 2019-06-25 05:45 UTC
I am trying to build osquery package from 3.4.0 branch. But build is failing saying CMakeLists.txt files were missing from multiple location. Could you please take a look at this?

**Comment by groob** [comment] 2019-06-25 10:16
Duplicate of #5601

**Closed by groob** 2019-06-25 10:16 UTC
