### ISSUE TITLE
Multiple wildcards in LIKE do not work for registry table

### ISSUE THREAD

**Issue by nmeocisco** [osquery/osquery#6778] opened 2020-11-30 18:41 UTC
# Bug report

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.19042 | 19042 | windows  |
+------------+-------+----------+
```
### What version of osquery are you using?

4.5.1

### What steps did you take to reproduce the issue?

Perform the following query:
```
SELECT key AS reg_key, path, name, data FROM registry WHERE path LIKE "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\%\Parameters";
```
This will return a bunch of results from services under `CurrentControlSet` in the registry. A query with `CurrentControlSet` replaced by `ControlSet001` will work as well:
```
SELECT key AS reg_key, path, name, data FROM registry WHERE path LIKE "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\%\Parameters";
```

Then perform the following query:
```
SELECT key AS reg_key, path, name, data FROM registry WHERE path LIKE "HKEY_LOCAL_MACHINE\SYSTEM\%\Services\%\Parameters";
```
This will return no rows.

### What did you expect to see?

Values returned from both `CurrentControlSet` and `ControlSet001` from inside the registry when using the query that contains two % wildcards.

### What did you see instead?

No results when using multiple % wildcards.

**Comment by directionless** [comment] 2021-01-30 03:45
As a workaround, you can do this with a JOIN. Select the first wildcard, concat, and join.

**Comment by artemist-work** [comment] 2022-08-09 19:07
I'm having trouble reproducing this on osquery HEAD, 5.4.0, and 5.3.0. Can you confirm if this is still an issue?

**Comment by zwass** [comment] 2022-08-09 19:53
From our testing, this seems to be fixed in recent versions. Please reopen if you find otherwise.

**Closed by zwass** 2022-08-09 19:53 UTC
Labels: triage, Windows
