### ISSUE TITLE
Query Run Before Extension Load

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#5680] opened 2019-07-31 23:54 UTC
# Bug report

### What operating system and version are you using?

OS: Windows 10 Enterprise RS3 x64 (10.0.16299)

### What version of osquery are you using?

Shell version: 3.3.2

### What steps did you take to reproduce the issue?
Using TrailOfBits extension 1.2 (https://github.com/osql/extensions)
Extension listed in extensions.load file, which is set to autoload via CLI flag.

Invocation:

> osqueryi.exe --json --verbose --disable_extensions=false --extensions_autoload=extensions.load "SELECT * FROM HostBlacklist"

### What did you expect to see?

No errors, expected output from quering the extension's HostBlacklist table.

### What did you see instead?

Extension found, ext mgr started, but query ran before extension loaded and registered (extension timeout/interval not respected).
> I0731 16:47:44.487181 17272 init.cpp:416] osquery initialized [version=3.3.2]
I0731 16:47:44.491226 17272 extensions.cpp:394] Found autoloadable extension: C:\osquery_extension_testing\ToB.ext.exe
I0731 16:47:44.491226 17272 database.cpp:563] Checking database version for migration
I0731 16:47:44.491226 17272 database.cpp:587] Performing migration: 0 -> 1
I0731 16:47:44.491226 17272 database.cpp:619] Migration 0 -> 1 successfully completed!
I0731 16:47:44.491226 17272 database.cpp:587] Performing migration: 1 -> 2
I0731 16:47:44.492197 17272 database.cpp:619] Migration 1 -> 2 successfully completed!
I0731 16:47:44.492197 13576 interface.cpp:265] Extension manager service starting: \\.\pipe\shell.em
I0731 16:47:44.492197 17272 auto_constructed_tables.cpp:86] Removing stale ATC entries
I0731 16:47:44.493197 17272 killswitch.cpp:60] enum osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0731 16:47:44.493197 17272 init.cpp:688] Error reading config: config file does not exist: \ProgramData\osquery\osquery.conf
I0731 16:47:44.493197 17272 killswitch.cpp:60] enum osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0731 16:47:44.501221 13704 watcher.cpp:629] Created and monitoring extension child (2152): C:\osquery_extension_testing\ToB.ext.exe
[
]
Error: no such table: HostBlacklist

Using 

> --extensions_require=<path_to_extensions>

 is a workaround, but listing all extensions I want to use on the command-line when they're already listed in the autoload file is far from ideal.  I would expect these "run-one-query-and-exit" scenarios to load and allow extensions to register prior to running the query received via command-line.

**Comment by Smjert** [comment] 2019-10-01 13:04
Thanks for the report!

Actually this is currently wanted behaviour, because one of the concerns was that loading all extensions immediately could result in unwanted behaviour (slow downs/hangs).
I'll close this since it's not a bug, I suggest reopening this as a feature request, specifying what you would like as wanted behaviour.
One thing I can think of is having an option which immediately loads all extensions specified in the autoload file, instead of having to list them.

**Closed by Smjert** 2019-10-01 13:04 UTC
Labels: Windows, bug, extensions
