### ISSUE TITLE
Shell history Query causes Thrift plugins to crash and be restarted

### ISSUE THREAD

**Issue by nickryand** [osquery/osquery#5326] opened 2018-12-13 21:40 UTC
# Bug report

### What operating system and version are you using?

```
# osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 16.04.5 LTS (Xenial Xerus)
   build =
platform = ubuntu
```
### What version of osquery are you using?

```
# osqueryi --line "SELECT version from osquery_info;"
version = 3.3.0
```

### What steps did you take to reproduce the issue?
Using the foobar_logger plugin
* https://github.com/osquery/osquery-python/blob/master/examples/foobar_logger.ext

The following `osquery.conf`
```
{
    "options": {
        "disable_audit": false,
        "audit_allow_config": true,
        "audit_persist": true,
        "disable_events": "false",
        "logger_plugin": "foobar_logger",
        "config_plugin": "filesystem",
        "events_expiry": 1
    },

    "schedule": {
        "shell_history": {
            "query": "SELECT * FROM shell_history JOIN users on (uid);"
            "interval": 5
        },
    }
}
```

Command Line Steps
```Bash
root@vagrant:~# osqueryi
Using a virtual database. Need help, type '.help'
osquery> select * from users join shell_history using (uid);
Thrift: Thu Dec 13 20:30:08 2018 TSocket::read() THRIFT_POLL() Interrupted system call
Thrift: Thu Dec 13 20:30:08 2018 TConnectedClient died: Unknown: Interrupted system call
osquery> Thrift: Thu Dec 13 20:30:12 2018 TSocket::open() connect() <Host:  Port: 0>Connection refused

osquery> select * from users join shell_history using (uid);
Thrift: Thu Dec 13 21:06:02 2018 TSocket::read() THRIFT_POLL() Interrupted system call
Thrift: Thu Dec 13 21:06:02 2018 TConnectedClient died: Unknown: Interrupted system call
osquery> W1213 21:06:05.807510  2001 interface.cpp:83] Refusing to register duplicate extension foobar_logger
Traceback (most recent call last):
  File "/usr/local/bin/foobar_logger.ext", line 23, in <module>
    version="1.0.0",)
  File "/usr/local/lib/python2.7/dist-packages/osquery/management.py", line 238, in start_extension
    message=status.message,
osquery.extensions.ttypes.ExtensionException: ExtensionException(code=1, _message=u'Duplicate extension registered', uuid=None)
Thrift: Thu Dec 13 21:06:06 2018 TSocket::open() connect() <Host:  Port: 0>Connection refused
W1213 21:06:08.749032  1991 watcher.cpp:595] Extension respawning too quickly: /usr/local/bin/foobar_logger.ext

osquery>
```

### What did you expect to see?

I am expecting the plugin interface to stay up and not require restarts of the plugin.

### What did you see instead?

THRIFT_POLL errors followed by plugin restarts. The more frequent this query is scheduled, the more often the plugin restarts.

**Comment by ostrowr** [comment] 2018-12-14 18:57
This is the same bug as https://github.com/kolide/osquery-go/issues/68 (I should have opened an issue here instead!) Managed to find the source of the bug but don't have a good fix.

**Comment by groob** [comment] 2019-01-15 15:17
I can also repro this:

```
I0115 15:12:50.147195    26 scheduler.cpp:83] Executing scheduled query known_hosts: select * from users cross join known_hosts using (uid);
Thrift: Tue Jan 15 15:12:50 2019 TSocket::read() THRIFT_POLL() Interrupted system call
Thrift: Tue Jan 15 15:12:50 2019 TConnectedClient died: Unknown: Interrupted system call

2019/01/15 15:12:52 extension ping failed: write unix @->/osq/osquery.sock: write: broken pipe
Thrift: Tue Jan 15 15:12:52 2019 TSocket::open() connect() <Host:  Port: 0>Connection refused
I0115 15:12:52.873929    19 extensions.cpp:304] Extension UUID 63914 has gone away
```

**Comment by groob** [comment] 2019-01-15 15:18
Related: https://github.com/facebook/osquery/issues/2875

**Comment by groob** [comment] 2019-01-15 15:21
I created a little extension for a repro-case. You'll need `Go 1.11+` installed and docker for mac to run `make run-container` and reproduce the problem.

https://github.com/kolide/osquery-issue-5326

The issue does not happen on macOS, just linux.

**Comment by akindyakov** [comment] 2019-01-18 13:16
I could not reproduce the problem on `experimental` branch.
```bash
[%] cat osquery.conf
{
    "options": {
        "disable_audit": false,
        "audit_allow_config": true,
        "audit_persist": true,
        "disable_events": "false",
        "logger_plugin": "foobar_logger",
        "config_plugin": "filesystem",
        "events_expiry": 1
    },
    "schedule": {
        "shell_history": {
            "query": "SELECT * FROM shell_history JOIN users on (uid);",
            "interval": 5
        }
    }
}
[%] buck build @mode/linux-x86_64/release osquery:osqueryd
[%] ./buck-out/release/gen/osquery/osqueryd --S --line "SELECT version, build, platform FROM os_version;"
[#] ./buck-out/release/gen/osquery/osqueryd --S --config_path=osquery.conf --extension foobar_logger.ext
```
Does it happens only on `master` ?

**Comment by groob** [comment] 2019-01-18 14:38
It's explicitly if you join `users` with shell_history. Running the query in reverse causes the query planner not to invoke the same apis. 

Here' are the queries I use:

```
    "shell_history": {
      "query": "select * from users cross join shell_history using (uid);",
      "interval": 5
    },
    "known_hosts": {
      "query": "select * from users cross join known_hosts using (uid);",
      "interval": 5
    },```

**Comment by akindyakov** [comment] 2019-01-23 11:10
Ok, as far as I can see the problem is in the dropping privileges in the other threads. According to [ref to bugzilla.redhat](https://bugzilla.redhat.com/show_bug.cgi?id=473907) in case of changing privileges glibc sends SIGRT_1 to other threads which lead to `poll` be interrupted. On posix we can not have different credentials for thread of one process. Therefore the solution is either to do not use dropping privileges for the whole osquery process or patch all usages of poll in thrift code. I like first option more because playing with permissions of the whole osqueryd can cause unpredicted interferences between threads. For instance the same table can provide different results because some other thread dropping and regaining privileges at the same time.

So, the solution for now I'd like to suggest is remove dropping privileges from safe places like reading files with known hostnames or shell history files. And because we can not interact with apt/rpm/yum databases as root and should drop to `none` user for it I'd suggest to increase the number of attempts to poll in case of `EINTR`. It can significantly eliminate the problem for now.

As a long term solution I'd suggest to move out risky code (e.g. apt/rpm/yum tables) to extensions in separated process and remove `dropTo` usages inside of `osqueryd` at least for linux (because on MacOS it possible to drop privileges for thread only as far as I know).

**Comment by groob** [comment] 2019-01-23 14:22
Thanks for looking more into this issue. I agree with the suggested approach, but I'm wary of breaking existing functionality. I'll mention this issue during office hours tomorrow and see if others have something more to add. 

RE: darwin (somewhat offtopic for this thread)
AFAIK this problem does not appear on macOS, but the issues with privilege dropping are much more complicated on mac. Depending on wether you run in the user context `osqueryd` or `sudo osqueryd` in a shell vs running from a LaunchDaemon, the privilege dropping APIs might not do what you expect. 
For example, I ran into an issue with using `pthread_setugid_np` to read the `DiscoverableMode` key in Airdrop Preferences and would get different behavior when launching osquery as a launchdaemon.

**Comment by akindyakov** [comment] 2019-01-24 13:32
I merged 2 patches, it's not gonna happen again. Can I ask you to test the new version from `experimental` branch?

**Comment by nickryand** [comment] 2019-03-14 05:52
I was unable to figure out how to build osqueryi from experimental. Testing using osqueryd looks to be working without any Thrift errors. Thanks for the fix!

**Comment by groob** [comment] 2019-03-14 17:59
@nickryand just an FYI, but osqueryd and osqueryi are the same binary, `osqueryi` is a symlink. You can create the symlink yourself or start the shell with `osqueryd -S`

**Comment by nickryand** [comment] 2019-03-14 21:26
I should probably RTFM... Thanks for the note 👍

**Comment by Smjert** [comment] 2019-10-12 16:17
I've tested this with the latest master and it seems to be resolved, closing.

**Closed by Smjert** 2019-10-12 16:17 UTC
Labels: Linux, bug, extensions
