### ISSUE TITLE
iptables: Show per-rule packet/byte counts instead of per-policy counts

### ISSUE THREAD

**Issue by djahandarie** [osquery/osquery#1921] opened 2016-03-11 23:51 UTC
Right now, the `iptables` table has `packets` and `bytes` columns. Confusingly (to me), all the rows in my output had the same values for these columns.

After looking through [osquery/tables/networking/linux/iptables.cpp](https://github.com/facebook/osquery/blob/master/osquery/tables/networking/linux/iptables.cpp), I realized that these columns do not correspond to the per-rule counters you see next to each rule when you run `iptables -L -v`, but instead the _policy_ counters.

It looks like the iptables API does expose a function to get the per-rule counters:

[struct ipt_counters *iptc_read_counter(const ipt_chainlabel chain, unsigned int rulenum, iptc_handle_t *handle);](http://www.tldp.org/HOWTO/Querying-libiptc-HOWTO/qfunction.html#AEN588)

I'm not sure if showing the policy counters instead of the per-row counters is considered a bug, but if the iptables table is intended to show information for rules, it's odd that it's showing information for policies instead. Either way, it would be very nice to have the per-rule counters accessible somehow.

**Comment by zwass** [comment] 2016-07-08 19:06
@djahandarie Besides for this, are you getting results that make sense from the `iptables` table? I tested it out in my dev VM and got the following:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo iptables -L -v
Chain INPUT (policy ACCEPT 346 packets, 20223 bytes)
 pkts bytes target     prot opt in     out     source               destination
   11   924 DROP       all  --  any    any     nuq04s29-in-f4.1e100.net  anywhere

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 279 packets, 20763 bytes)
 pkts bytes target     prot opt in     out     source               destination
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo ./build/trusty/osquery/osqueryi
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery> select * from iptables;
+-------------+---------+--------+--------+----------+--------------+-----------------+---------+--------------+---------+----------+----------+---------------+-------+---------+-------+
| filter_name | chain   | policy | target | protocol | src_ip       | src_mask        | iniface | iniface_mask | dst_ip  | dst_mask | outiface | outiface_mask | match | packets | bytes |
+-------------+---------+--------+--------+----------+--------------+-----------------+---------+--------------+---------+----------+----------+---------------+-------+---------+-------+
| filter      | INPUT   | ACCEPT | DROP   | 0        | 216.58.192.4 | 255.255.255.255 | all     |              | 0.0.0.0 | 0.0.0.0  | all      |               | yes   | 383     | 22002 |
| filter      | INPUT   | ACCEPT | DROP   | 0        | 216.58.192.4 | 255.255.255.255 | all     |              | 0.0.0.0 | 0.0.0.0  | all      |               | yes   | 383     | 22002 |
| filter      | FORWARD | ACCEPT | DROP   | 0        | 216.58.192.4 | 255.255.255.255 | all     |              | 0.0.0.0 | 0.0.0.0  | all      |               | yes   | 0       | 0     |
| filter      | OUTPUT  | ACCEPT | DROP   | 0        | 216.58.192.4 | 255.255.255.255 | all     |              | 0.0.0.0 | 0.0.0.0  | all      |               | yes   | 310     | 23130 |
+-------------+---------+--------+--------+----------+--------------+-----------------+---------+--------------+---------+----------+----------+---------------+-------+---------+-------+
```
I would expect that one of these lines would correspond to that `DROP` rule I have...

@javuto on Slack says he wrote it long ago and hasn't used it since.

I guess what I'm trying to figure out is, does the table work at all? It might need an entire overhaul.

**Comment by theopolis** [comment] 2016-07-08 21:51
I think the table is working to a degree, there's absolutely some ambiguity. There may also be bugs within the interpretation of fields from the netfilter API calls. Let's consider this table buggy and get to work on making it useful soon.

**Comment by Smjert** [comment] 2020-10-24 13:35
Done a quick test on an Ubuntu 18.04 VM with latest master (d71420be93a35ad810646110e0e13c679a6521c3), the issue is still relevant.

**Comment by directionless** [comment] 2024-02-18 03:53
While I'm sure it's relevant, `iptables` is deprecated and I'm going to close this. Any effects here should be focused on nftables

**Closed by directionless** 2024-02-18 03:53 UTC
Labels: virtual tables, Linux, triage
