### ISSUE TITLE
rpm tables broken on fedora 33

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6938] opened 2021-02-05 16:35 UTC
# Bug report

### What operating system and version are you using?

fedora 33, as tested with docker:
```
docker run --rm -v /tmp/osq-linux:/osq -i -t fedora:33
```

Seems fine on fedora:32

### What version of osquery are you using?

Testing with both `4.6.0` as well as the CI built [`4.6.0-80-g0e1de30e`](https://github.com/osquery/osquery/commit/0e1de30ec8fb98b42744b3162cbeca5392cb1a34)

This commit includes #6850 which I thought would have fixed this

### What did you see instead?

```
osquery> select * from rpm_packages;
I0205 16:34:55.867463    64 glog_logger.cpp:49] RPM notice: Failed to read auxiliary vector, /proc not mounted?
I0205 16:34:55.869980    64 glog_logger.cpp:49] RPM notice: using dummy database, installs not possible
```

**Comment by directionless** [comment] 2021-02-05 17:09
This is definitely breakage related to the new sqlite format

**Comment by theopolis** [comment] 2021-02-05 17:11
I think this is a duplicate of https://github.com/osquery/osquery/issues/6895

**Closed** 2021-02-05 17:11 UTC
Labels: Linux, duplicate, virtual tables

**Comment by directionless** [comment] 2021-02-05 17:12
Yes, it's a dup. Sorry

**Comment by amr8457** [comment] 2021-02-09 13:16
Can connection￼
