### ISSUE TITLE
Firefox extensions not listed in osquery on Ubuntu 22.04 and 24.04

### ISSUE THREAD

**Issue by neyaadeez** [osquery/osquery#8424] opened 2024-09-19 19:10 UTC
# Bug report

### What operating system and version are you using?

Output:
```
version = 22.04.4 LTS (Jammy Jellyfish)
build = 
platform = ubuntu

version = 24.04 LTS (Nobel Numbat)
build = 
platform = ubuntu
```

### What version of osquery are you using?

Output:
```
version = 5.12.1
```

### What steps did you take to reproduce the issue?

```bash
osqueryi --line "SELECT * from firefox_addons;"
```

### What did you expect to see?

Expected output of the Firefox extension query:
```
uid = 1000
name = Form Autofill
identifier = formautofill@mozilla.org
creator = null
type = extension
version = 1.0.1
description = 
source_url = null
visible = 1
active = 1
disabled = 0
autoupdate = 1
location = app-system-defaults
path = /opt/firefox/browser/features/formautofill@mozilla.org.xpi

uid = 1000
name = Firefox Screenshots
identifier = screenshots@mozilla.org
creator = Mozilla <screenshots-feedback@mozilla.com>
type = extension
version = 39.0.1
description = Take clips and screenshots from the Web and save them temporarily or permanently.
source_url = null
visible = 1
active = 0
disabled = 1
autoupdate = 1
location = app-system-defaults
path = /opt/firefox/browser/features/screenshots@mozilla.org.xpi
```

### What did you see instead?

The query returns empty.

**Comment by michael-myers** [comment] 2024-11-01 18:33
I tested the latest osquery on Ubuntu 24.04.1, x86_64, and I get the right results from `select * from tirefox_addons`.

First, are you running osquery as the user with Firefox? If you are running as root, it will return empty results, but print a message explaining that this is the intended behavior, explained in [this blog post](https://medium.com/@mthomas_28262/osquery-consider-joining-against-the-users-table-9277dd84481c). You can try the query as `select username, name AS add-on_name FROM users CROSS JOIN firefox_addons USING (uid);` and it will show which user has which add-ons, even when running osquery as root.

If this is not your situation, you can run osquery with `--verbose` and do `select * from firefox_addons` and look for clues about `Failed to read the extensions file`. It might be looking for the wrong location for the Firefox installation. I tested using Firefox installed via snap.

**Comment by michael-myers** [comment] 2024-12-17 06:22
Closing this issue as I think my last response might have been relevant, but if the original reporter wants to raise the issue again with a response, they can.

**Closed by michael-myers** 2024-12-17 06:22 UTC
Labels: bug, virtual tables, Linux, triage
