### ISSUE TITLE
Recursive search on registry table with while 

### ISSUE THREAD

**Issue by miketmorley** [osquery/osquery#7389] opened 2021-11-18 21:26 UTC
# Feature request

### What new feature do you want?

Recursive selects on Registry table do not perform recursively if there is an embedded wildcard in the path or key.
Example (non-recursive)
SELECT * FROM registry
WHERE
path LIKE 'HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive\%';

This query returns the same results as the one above.
SELECT * FROM registry
WHERE
path LIKE 'HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive\%%';

However if you specify a specific user SID rather than wildcard, it does behave recursively.

### How is this new feature useful?

From a security perspective it is useful to perform a recursive search under HKEY_USERS for all users on the system. An example is to scan the registry under HKU\%\Software\Microsoft\Office to see which office macros are enabled and disabled. 

Additionally multiple wildcards in registry paths don't see to work. E.g. 
select * from registry where path LIKE 'HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive\%;
returns no results

### How can this be implemented?

Useful to run recursive queries under HKU for all users.

**Comment by Smjert** [comment] 2021-12-30 17:10
Today I stumbled upon this feature while looking at something else and found the reason of the unexpected behavior, but also a simple workaround to it.
The recursion is actually present if you write the query as `HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive%%`.

The registry key path pattern logic is a bit nuanced, I'll try to explain here how it works so that there's a better understanding (and then maybe we can either discuss changing something or have better docs!).


# (Long) Explanation

First of all one has to realize that there are two pattern matchings at play:
1. The `registry` table pattern matching
2. The SQL pattern matching, which is the filtering done by SQLite when the table returns the rows from the previous step.

The table logic wants to understand the pattern as a registry key path made of components separated by a `\`, with some special exceptions for `%` and `%%`.
I'll try to give the stages and the steps of the algorithm and then expand it later with examples.


## Stage 1: Table logic pattern extraction

This is done only once at the start and if the constraint is on the `path` column

Does the pattern ends with a `%%`?:
1. Yes -> Use the full pattern
2. No -> Extract the pattern up to and excluding the last `\`. If none is found, use the full pattern

Otherwise if the constraint is on the `key` column, the full pattern is always used.

Examples:
`path LIKE 'HKEY_USERS%\'` -> `HKEY_USERS%`
`path LIKE 'HKEY_USERS%'` -> `HKEY_USERS%`
`path LIKE 'HKEY_USERS\%'` -> `HKEY_USERS`
`path LIKE 'HKEY_USERS\%%'` -> `HKEY_USERS\%%`
`path LIKE 'HKEY_USERS%%'` -> `HKEY_USERS%%`
`key LIKE 'HKEY_USERS\%'` -> `HKEY_USERS\%`


## Stage 2: Table logic pattern matching

This is done once, but it internally has a loop:
1. Split the pattern into path components using the `\`.
2. If the **first** path component ends with `%%` -> populate the results with a list of default keys (registry hives), then use those keys to do a recursion on each one and go to Stage 3
3. If it doesn't then there are two additional cases:
   a. The **first** component contains a `%` -> populate the results with a list of default keys and remove the first component from the remaining ones.
   b. It does not contain a `%` -> add the path component as a key to the results and remove that component from the remaining ones
4. Loop through all the remaining components, checking for these three cases:
   a. The component contains a `%%` -> Use all the previously obtained keys and recurse on them, adding the found keys into the results, until no more can be found, then go to Stage 3.
   b. The component contains a `%` -> Use all the previously obtained keys as a base path and add all their subkeys, one level down, to the results. Remove the processed component and go back to step 4.
   c. The component doesn't have any special matching character, so loop through all the previously obtained keys and append that path component as is. Remove the processed component and go back to step 4.
5. Return all the obtained keys


## Stage 3: Table logic final pass

Loop through all the obtained keys, querying their information **and** subkeys, one level down, creating a row for each one of them.


## Stage 4: SQLite filtering

Do a **string** pattern matching on each key, so that the final rows shown are the ones that satisfy that match.


## Examples

### Example 1

To start simple, lets take the following constraint and their stage 1 result:
1. `path LIKE 'HKEY_USERS%\'` -> `HKEY_USERS%`
2. `path LIKE 'HKEY_USERS%'` -> `HKEY_USERS%`
3. `path LIKE 'HKEY_USERS\%'` -> `HKEY_USERS`
4. `path LIKE 'HKEY_USERS'` -> `HKEY_USERS`

The first two yield the same initial pattern and due to Stage 2, step 3a, in both cases we internally get a list of default keys taken from here:
https://github.com/osquery/osquery/blob/4274d3bfaedbcf7fa2b7b225abc2c2fb1b1b2e5a/osquery/tables/system/windows/registry.cpp#L55-L63

Then since there are no other path components in the pattern, the logic directly goes to Stage 3, so all the subkeys of those default keys, one level down, will be returned by the table. Worth noting that the returned keys are in the thousands.

Finally at Stage 4 it will use SQLite filtering to actually return only what we have asked. The first pattern won't yield any result because no path ends with `\`, while the second pattern will return only the `HKEY_USERS` subkeys.

The third pattern instead will go through Stage 2 step 3b, then 5, returning `HKEY_USERS` as the only key.
Finally at Stage 3 it will return all the subkeys of `HKEY_USERS`, one level down, and then filtering will happen at Stage 4.

Note that the second and third constraint return the same results, but the third one is faster because it internally only returns the subkeys of `HKEY_USERS` to be filtered.
You can check this using the `--planner` flag and you will notice that for the first and second pattern osquery will print a log line telling something like `osquery planner: xFilter registry generate returned row count:4456`, while for the third one it will be much less, `osquery planner: xFilter registry generate returned row count:6`

The fourth pattern is the same as the third, but at the SQLite filtering stage it will filter out all of the results, because none of them exactly matches `HKEY_USERS`.


### Example 2

Going a step further with another example (and maybe showing something unexpected):
1. `path LIKE 'HKEY_USERS%\SOFTWARE'` -> `HKEY_USERS%`
2. `path LIKE 'HKEY_USERS\%\SOFTWARE'` -> `HKEY_USERS\%`
3. `path LIKE 'HKEY_USERS\%\SOFTWARE%'` -> `HKEY_USERS\%`

The first pattern is not equivalent to the other two, not only because of the parsed pattern, but due to that special case on the first component, which is containing `%`.
With the first pattern we lose on level of depth, because at Stage 4 we will have the default keys plus their subkeys obtained at Stage 3, but those will not contain `SOFTWARE` which is one step below.

In the other two cases the first component (`HKEY_USERS`) is directly added to the results as in Stage 2 step 3b instead, then the second component (`%`) gets processed in step 4b, which will take the previous results (only `HKEY_USERS`) and obtain their subkeys one level down.
So you will have keys like `HKEY_USERS\S-1-5-19`, `HKEY_USERS\S-1-5-20`.
Due to Stage 3 then another level of subkeys of those previously found keys is added and some of them will end with `SOFTWARE`, which will be filtered by Stage 4.


### Example 3

This should finally explain why `path LIKE 'HKEY_USERS%\SOFTWARE\Microsoft\OneDrive%%'` was not working as expected. That very first component is eating one level of the "recursion".
Additional thing to note is that the final component `OneDrive%%` as with `OneDrive%` will recurse or loop starting from the previous path component, which means that it will return first all the keys under `Microsoft` and then recurse or loop those, vs `OneDrive\%%` which will only recurse keys under the `OneDrive` path, which might be what you actually want.

There **is** maybe though an annoying difference, which is that without recursing all the keys under `Microsoft`, the second faster pattern will not return the `OneDrive` key itself.
For a workaround could ne to put a second constraint in OR like `HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive\%%' OR path LIKE 'HKEY_USERS\%\SOFTWARE\Microsoft\OneDrive'`.
Although the query is longer, this yields much less results internally than the `OneDrive%%` version (263 vs 3334 in my case).

There's a caveat though, which is that if an error happens, like a key cannot be accessed due to permissions or because it's not found, then partial results will be returned.
The second case is now considered a bug and will be resolved by the fix here https://github.com/osquery/osquery/pull/7414

**Comment by directionless** [comment] 2021-12-30 20:34
I think this is very similar to how the augeas table filtering I wrote works. The constraints around the path separators get funny

**Comment by Smjert** [comment] 2023-12-11 17:45
I'm going to close this issue since the recursione of keys is implemented, it's just that the table is a bit finicky.

**Closed by Smjert** 2023-12-11 17:45 UTC
Labels: wishlist, Windows
