### ISSUE TITLE
osqueryi permanently frozen while querying routes

### ISSUE THREAD

**Issue by Addvilz** [osquery/osquery#6636] opened 2020-09-06 20:14 UTC
# Bug report

`SELECT * FROM routes` permanently freezes `osqueryi` and never returns. 

### What operating system and version are you using?

CentOS Linux release 8.2.2004 (Core)

### What version of osquery are you using?

4.4.0

### Additional info

This is a very odd bug - I tried to pinpoint what exactly is causing it, but no luck. It only seems to affect some installations, but not others. Tested on multiple pretty much identical hosts, same versions, same OS core, identical networking (less addresses themselves), same packages, same dependencies. In some, the query works perfectly fine, on some, freezes permanently and forever.

```
default via X.X.X.254 dev eno1 proto dhcp metric 101 
default via Y.Y.Y.2 dev bridge0 proto static metric 425 
Y.Y.Y.0/16 dev bridge0 proto kernel scope link src Y.Y.Y.2 metric 425 
X.X.X.0/24 dev eno1 proto kernel scope link src X.X.X.190 metric 101 
Z.Z.Z.0/24 dev virbr0 proto kernel scope link src Z.Z.Z.1 metric 426
```

Less the actual addresses, routing tables for all the hosts are also identical.

EDIT: more info - the query also freezes when issued via python client. So the issue is probably in `osqueryd`.

**Comment by theopolis** [comment] 2020-09-09 15:33
Thanks for the info @Addvilz, are you able to test debug versions of osquery on these affected machines? For example, if I tried to identify and fix the issue, would you be able to pull the updated code, build it, and test?

**Comment by Addvilz** [comment] 2020-09-09 16:24
@theopolis that would be problematic since I am not able to reproduce this myself any longer. However I do believe I have at least some clue what could be causing this.

For context, there are 8 almost equal hosts I have set up in a nearly identical way (ansible, yay) except for networking which I did manually. Now, from these 8 hosts, `osqueryi` was failing in the manner I mentioned on 3 out of the total 8. Although I was not able to initially determine what was the difference I missed, today I noticed all 3 failing hosts have IPv6 enabled, but the working ones have IPv6 disabled (IPV6INIT=no).

Since IPv6 is not desired on these hosts, I disabled it, and look and behold - `osqueryi` is working perfectly now. Now comes the weird part - I tried to re-introduce the issue by enabling the IPv6 on the interfaces again, again in DHCP mode - but nothing, `osqueryi` still works as expected.

Slight oversight on my part is that before doing this change I did not record output of `ip -6 route`, but I do believe this issue is ultimately caused by some malformed/invalid/badly advertised routes that were left over from the initial setup of the host. Unfortunately that information is lost now, but I hope that is enough to help you identify where the issue might be. 

My bet would be that osqueryd attempts to do some process X with IPv6 routes during the list query, and something causes it to freeze forever, and introducing some obvious or not so obvious IPv6 addresses in routes/addrs of a test should break it. 

Let me know if there is anything else I can do here.

**Comment by theopolis** [comment] 2020-09-11 18:21
No worries, what kernel version are these failing hosts? I ask because it might be that the `netlink` read is hanging.

**Comment by Addvilz** [comment] 2020-09-11 18:39
Sure - `4.18.0-193.14.2.el8_2.x86_64`

**Comment by theopolis** [comment] 2020-09-11 19:11
Hm, I saw some notes about 4.1-4.2 having issues. But either way I think we can set a timeout on the socket without causing any sort of regression.

**Comment by Addvilz** [comment] 2020-09-11 19:33
Could be a good idea because 4.18 is the default shipped with EL 8, meaning this could potentially affect any new EL8 based installations with "odd" network configs.

**Comment by theopolis** [comment] 2021-02-21 21:01
This is a duplicate of https://github.com/osquery/osquery/issues/5276 (I am trying to condense duplicated bug reports)

**Closed by theopolis** 2021-02-21 21:01 UTC
Labels: Linux, triage, virtual tables
