### ISSUE TITLE
osqueryi output JSON data format error if table data has chinese world

### ISSUE THREAD

**Issue by turtlejamesw** [osquery/osquery#4737] opened 2018-07-20 02:49 UTC
Dear all,
I try to output data to json format, and sometime json data format error if data has chinese world
details are as follows -
F:\>osqueryi.exe --json "select friendly_name from interface_addresses"
[
  {"friendly_name":"@?? 2"},
  {"friendly_name":"@?? 2"},
  {"friendly_name":"Y*莎"},
  {"friendly_name":"Y*莎"},
  {"friendly_name":"VMware Network Adapter VMnet1"},
  {"friendly_name":"VMware Network Adapter VMnet1"},
  {"friendly_name":"VMware Network Adapter VMnet8"},
  {"friendly_name":"VMware Network Adapter VMnet8"},
  {"friendly_name":"Wi-Fi"},
  {"friendly_name":"Wi-Fi"},
  {"friendly_name":"Bluetooth 莎#?},     <===== lost "
  {"friendly_name":"Bluetooth 莎#?},     <===== lost "
  {"friendly_name":"Bluetooth 莎#?},     <===== lost "
  {"friendly_name":"Loopback Pseudo-Interface 1"},
  {"friendly_name":"Loopback Pseudo-Interface 1"},
  {"friendly_name":"@?? 5"},
  {"friendly_name":"@?? 5"}
]

**Comment by turtlejamesw** [comment] 2018-07-27 08:57
i found os_version, interface_addresses, users, programs, drivers tables also has same problem

**Comment by akindyakov** [comment] 2018-07-31 10:05
Oh, I see. Yes, the problem is widespread across windows code :(
But unfortunately I can't see small solution for all tables. Let's fix it one by one.

**Comment by directionless** [comment] 2020-07-07 04:02
I believe there's been a fair bit of work around the character set handling on windows. Given the age of this, and the lack of easy test case, I'm going to close this. Feel free to reopen or comment if this is ongoing with the current version.

**Closed by directionless** 2020-07-07 04:02 UTC
Labels: Windows, bug, debt
