### ISSUE TITLE
Implement startup_items for Linux

### ISSUE THREAD

**Issue by fmanco** [osquery/osquery#4392] opened 2018-05-14 21:49 UTC
Ideally this will support

- [x] SystemD
- [x] SysV
- [ ] Upstart

These are by order of priority.

**Comment by guliashvili** [comment] 2018-05-14 22:01
Hi,

So far, I just looked for how to support SystemD.

SystemD exposes dbus interface ( With their own implementation sd-bus). 

This is their blog post about sd-bus. http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html
And this is how they call sd-bus interface https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl.c#L1486-L1560

However for that, we have to install  libsystemd-dev ( http://manpages.ubuntu.com/manpages/xenial/man3/sd-bus.3.html )

Please, let me know your thoughts.

**Comment by mike-myers-tob** [comment] 2020-05-29 00:00
Duplicate of https://github.com/osquery/osquery/issues/3627

**Comment by rcipkins** [comment] 2020-06-16 16:45
Is it still a priority for the table to support Upstart? New developments to Upstart ended a few years ago in favor is systemD and I am not sure how many systems still use it.

**Comment by mike-myers-tob** [comment] 2020-06-16 17:35
> Is it still a priority for the table to support Upstart? New developments to Upstart ended a few years ago in favor is systemD and I am not sure how many systems still use it.

Maybe the answer to this depends on what versions of Linux are officially supported by osquery. I thought we had that list somewhere but I couldn't find it.

**Comment by Smjert** [comment] 2020-06-16 17:55
We are still targeting (best-effort) CentOS 6, which would be the oldest.
Although November 30th, 2020 maintenance updates will stop for it.

For Ubuntu the oldest is 16.04.
I would say that those distributions are the ones we support/test with.

**Comment by mike-myers-tob** [comment] 2021-01-25 22:44
With #6502 and #6562 the SysV and SystemD autostart locations are covered. Because CentOS 6 is now EOL, Upstart is probably a "won't implement" at this point (even though osquery continues to support CentOS 6 for now), so I will close this issue.

**Closed by mike-myers-tob** 2021-01-25 22:44 UTC
Labels: Linux, feature, virtual tables
