### ISSUE TITLE
Poor performance querying python_packages on Windows

### ISSUE THREAD

**Issue by Breakwell** [osquery/osquery#6679] opened 2020-09-28 15:33 UTC
# Bug report

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.17763 | 17763 | windows  |
+------------+-------+----------+
```
### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 4.4.0   |
+---------+
```

### What steps did you take to reproduce the issue?

Install python with many dependencies on Windows, I have done a pip freeze on the machine I was using:
[requirements.txt](https://github.com/osquery/osquery/files/5293293/requirements.txt)

Run query:

```
SELECT name, version, summary, author, license, `path`, directory
FROM python_packages
```

### Description

When running with the watchdog on it managed to stop osquery due to high CPU usage. I found osquery was spending the bulk of it's time in listDirectoriesInDirectory:

https://github.com/osquery/osquery/blob/master/osquery/tables/system/python_packages.cpp#L80

I wrapped it up in some timers to check it's performance:

```
void genSiteDirectories(const std::string& site, QueryData& results) {
  std::vector<std::string> directories;

  auto t1 = std::chrono::high_resolution_clock::now();
  if (!listDirectoriesInDirectory(site, directories, true).ok()) {
    return;
  }
  auto t2 = std::chrono::high_resolution_clock::now();

  auto duration =
      std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

  std::cout << "Scanning site '" << site << " took " << duration << " milliseconds" << std::endl;
  std::cout << "Found " << directories.size() << " directories" << std::endl;
...
```
Output:
```
osquery> SELECT name, version, summary, author, license, `path`, directory FROM python_packages WHERE name='blah';
Scanning site 'C:\Python27-64\' took 1557 milliseconds
Found 185 directories
Scanning site 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\' took 5333 milliseconds
Found 371 directories
Scanning site 'C:\Python37\' took 10378 milliseconds
Found 2005 directories
```
I then replaced listDirectoriesInDirectory with a std implementation : 
```
void genSiteDirectories(const std::string& site, QueryData& results) {
  std::vector<std::string> directories;

  auto t1 = std::chrono::high_resolution_clock::now();
  for (const auto& entry : fs::recursive_directory_iterator(site))
    if (fs::is_directory(entry))
      directories.push_back(entry.path().string());
  auto t2 = std::chrono::high_resolution_clock::now();

  auto duration =
      std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

  std::cout << "Scanning site '" << site << "' took " << duration << " milliseconds" << std::endl;
  std::cout << "Found " << directories.size() << " directories" << std::endl;
...
```
Output:
```
osquery> SELECT name, version, summary, author, license, `path`, directory FROM python_packages WHERE name='blah';
Scanning site 'C:\Python27-64\' took 35 milliseconds
Found 185 directories
Scanning site 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\' took 198 milliseconds
Found 371 directories
Scanning site 'C:\Python37\' took 206 milliseconds
Found 2005 directories
```
I don't know if this is a bug in listDirectoriesInDirectory or if it just has unnecessary over head when used here.

**Comment by marcosd4h** [comment] 2023-03-29 13:55
I've just pushed PR7974 to address this.

There was a 10x performance increase when using the suggested logic (see `osqueryi_custom.exe` results below)

The logic is only used when running `python_packages` on Windows since I've not benchmarked `osquery::listDirectoriesInDirectory` on different OSes to see if the problem is also there. We can think of replacing  `osquery::listDirectoriesInDirectory` in the future with the `stdListDirectoriesInDirectory` logic if proper benchmarks are done on other OSes.

```
PS C:\tools\osquery> Measure-Command { .\osqueryi_5.8.2.exe "select COUNT(*) from python_packages;" | Out-Default }
+----------+
| COUNT(*) |
+----------+
| 228      |
+----------+
TotalSeconds      : 19.1131021
TotalMilliseconds : 19113.1021



PS C:\tools\osquery> Measure-Command { .\osqueryi_custom.exe "select COUNT(*) from python_packages;" | Out-Default }
+----------+
| COUNT(*) |
+----------+
| 228      |
+----------+
TotalSeconds      : 1.907992
TotalMilliseconds : 1907.992
```

**Comment by marcosd4h** [comment] 2023-06-30 14:21
Closing this as #7974 was already merged

**Closed by marcosd4h** 2023-06-30 14:21 UTC
Labels: virtual tables, performance, Windows
