### ISSUE TITLE
`xprotect_reports` table does not work on macOS Catalina

### ISSUE THREAD

**Issue by zgdatadoghq** [osquery/osquery#6588] opened 2020-08-11 03:19 UTC
# Bug report

### What operating system and version are you using?
+---------+--------+----------+
| version | build  | platform |
+---------+--------+----------+
| 10.15.4 | 19E266 | darwin   |
+---------+--------+----------+

### What version of osquery are you using?
+---------+
| version |
+---------+
| 4.3.0   |
+---------+

### What steps did you take to reproduce the issue?
- Create a helloworld.c with following code:
`int main(int argc, char *argv[])
{
    char unitBoth[] = "\x89\xC1\xC1\xE9\x07\x48\x69\xC9\x11\x08\x04\x02\x48\xC1\xE9\x20\x69\xC9\x80\x3F\x00\x00\xF7\xD9";
    return 0;
}`
- Compile it `xcrun clang helloworld.c`
- Run the program `./a.out` and hit `Report` button
- Run Osquery `select * from xprotect_reports;`

### What did you expect to see?
I expect Osquery `select * from xprotect_reports;` to return a report entry for the corresponding binary `a.out`.

### What did you see instead?
Osquery `select * from xprotect_reports;` returned empty result.

**Comment by mike-myers-tob** [comment] 2020-09-24 01:36
I followed @zgdatadoghq 's steps and it does trigger XProtect to submit a report to Apple, and indeed the `xprotect_reports` table appears to remain empty. (If doing this does not trigger XProtect, you may be working in a dev VM with SIP disabled; check with `csrutil status`)

A couple of things I noticed:
1. the XProtect list is not where this table is looking for it, but there is an alias there to the actual location, which is `/Library/Apple/System/Library/CoreServices/XProtect.bundle/Contents/Resources/`
1. Even after submitting a report to Apple, I don't see any evidence of the XProtect report files in the location that the virtual table is looking for them (`~/Library/Logs/DiagnosticReports`). Maybe this is the problem? Can you say with confidence that XProtect has been triggered here, and if so, where is the report? Let's start with a known use-case that generates an XProtect report file for sure.

Tested with osquery 4.5.0 and macOS 10.15.6.

**Comment by mike-myers-tob** [comment] 2020-09-28 21:26
Confirmed using a file event listener on macOS 10.15.7 that no files are created as the result of an XProtect detection, so as of Catalina, the osquery `xprotect_reports` table is dead in the water I think.

@theopolis do you think it should be disabled when running on macOS 10.15? It still serves its purpose on 10.14 and earlier. Apple is still providing security updates for 10.13 and 10.14 as of now.

**Comment by Oneiroi** [comment] 2022-09-02 13:54
This is an issue in macOS 12.5.x also and should be resolved, as many are using the `xprotect_reports` table to check for the interception of malware via XProtect, indeed there are Xprotect advancements coming in future macOS versions (https://arstechnica.com/gadgets/2022/08/apple-quietly-revamps-malware-scanning-features-in-newer-macos-versions/) if this is not fixed for the current implementation this certainly needs a revamp for when the updated feature is available.

**Comment by mike-myers-tob** [comment] 2022-09-02 17:56
@directionless @alessandrogario @sharvilshah how do folks feel about deprecating this `xprotect_reports` table and just resurrecting it later if we can. It is currently just non-working functionality in osquery.

**Comment by directionless** [comment] 2022-09-09 01:49
@terracatta On slack you mentioned you were unable to reproduce this. Can you say more?

@mike-myers-tob Hrm. Reading through some of the eclecticlight posts, I think we need to figure out some things:
1. Are there still reports?
2. Can we detect that they're generated? (maybe logs)
3. Apparently there are now regular scans
4. Can we detect those?

**Comment by terracatta** [comment] 2022-09-09 16:45
This table works great with the EICAR file, the diagnostic report is generated. With the malware created as the test case in the example no diagnostic report is ever generated. Seems like a bug in macOS.

**Comment by Oneiroi** [comment] 2022-09-12 18:46
The example given by @zgdatadoghq is for the following Yara rule:

```
rule XProtect_MACOS_b17a97e
{
meta:
description ="MACOS.b17a97e"
strings:
$s1 = { 89 C1 C1 E9 07 48 69 C9 11 08 04 02 48 C1 E9 20 69 C9 80 3F 00 00 F7 D9 }
condition:
Macho and filesize < 100KB and all of them
}
```

This is for the intercept of the OSX.Casso malware though this was trivially worked around through padding taking the size above 100Kb .

Here the example size on disk is 33Kb so is being caught:


The logs from `/Library/Logs/DiagnosticReports` note the following:

```
{"message":{"Count":1,"bundleIdentifier":null,"bundleVersion":null,"cdhash":"01ed682b45eb68e5556a4db398d706fa0b0f1671","fileIdentifier":"gh","fileSize":36404706,"isLibrary":false,"isQuarantined":false,"isSigned":true,"isUsed":true,"isValid":true,"mainExecutableHash":"b15fdb648373983d4ef8d31265abf12c2f9cb04b5afebdc44d66b2d9d7be478a","responsibleFileIdentifier":"Terminal.app/Contents/MacOS/Terminal","signatureTimestamp":1661418460,"signingIdentifier":"a.out","teamIdentifier":null},"name":"ExecutableMeasurementRawAggregatedData3","sampling":100,"uuid":"3052871a-7d51-4087-b1e2-513a25236db7_2"}
```

This does not create an `xprotect_reports` entry; whilst the eicar sample does; the logs from the same path are as follows:

```
{"message":{"Count":1,"bastion_pipeline_id":"8590218D-7D49-40BF-8F4F-1740291DCA6B","bastion_version":"72","build_configuration":null,"execution_duration":0.04983091354370117,"plugin_identifier":"Eicar","plugin_version":1,"status_code":"NoThreatDetected","status_message":"NoThreatDetected"},"name":"Bastion_Events_Completions_v1","sampling":10,"uuid":"5c445d8e-1ac1-46c7-9616-bb7dc9180a09_5"}
```


Both populate `/Library/Logs/DiagnosticReports/Analytics-Daily-YYYY-MM-DD-NNNNNN.NNNN.core_analytics` file on disk.

Suspect this is as with the first sample, whilst xprotect is working as intended and killing the suspected malware; it is not resolving to a "team":

```
"teamIdentifier":null
```

This is a current working theory, need to delve into [xprotect.cpp](https://github.com/osquery/osquery/blob/master/osquery/tables/system/darwin/xprotect.cpp) to confirm/deny the theory I suspect.

**Comment by tutasla** [comment] 2023-01-31 19:19
My notes after successfully testing for MACOS.b17a97e rule on Monterey 12.6.2

I can reproduce the issue by following the original steps. There are no new entries in `~/Library/Logs/DiagnosticReports` after running the program and hitting report. I noticed in the logs that ASP (Gatekeeper?) didn't allow the execution.
```
% sudo log show --last 20m | grep "Security policy"
2023-01-31 23:48:58.115717+0600 0x76f10    Default     0x0                  0      0    kernel: (AppleSystemPolicy) ASP: Security policy would not allow process: 7384, /private/tmp/a.out
```

Then I downloaded the `eicar.com` file. Because it is just a text file, I had to rename it to `eicar` and make it executable. You also can't run the eicar file from the terminal. After double-clicking on the eicar file and reporting it, a new XProtect diagnostic report gets created. However, the logs are now different. There are no more ASP logs.
```
% sudo log show --last 20m | grep -A 25 "violation"
2023-02-01 00:00:22.112774+0600 0x77eca    Error       0x0                  365    0    sandboxd: [com.apple.sandbox.reporting:violation] Sandbox: garcon(6629) deny(1) file-read-xattr /Users/user/Downloads/eicar
Violation:       deny(1) file-read-xattr /Users/user/Downloads/eicar
...
```

So what is going on? Let's check file attributes because Gatekeeper cares a lot about it. 
```
% xattr a.out 
(empty result)

 % xattr eicar 
com.apple.macl
com.apple.quarantine
```

Our compiled program has no attributes. The eicar file has the quarantine flag because it was downloaded from the Internet.

I think this is the bug. So to make XProtect reports appear, one must launch the "malware" from Finder under normal circumstances (i.e. download and execute malware).

1. Open your file system in a browser, for example `file:///private/tmp/`
2. Download `a.out` to get the quarantine flag
3. Rename it to `a` and make it executable `chmod +x a`
4. Double click on the program in Finder
5. Check `~/Library/Logs/DiagnosticReports` for new XProtect reports.

Finally, check the `xprotect_reports` table
```
osquery> select * from xprotect_reports;
+-----------------+-------------+------------+
| name            | user_action | time       |
+-----------------+-------------+------------+
| OSX.eicar.com.i | trash       | 1675181201 |
| OSX.eicar.com.i | trash       | 1675181201 |
| MACOS.b17a97e   | trash       | 1675189183 |
+-----------------+-------------+------------+
```

**Comment by mike-myers-tob** [comment] 2023-06-16 06:09
Reading the above, it seems like we can close this issue then, as it's not an osquery bug, just a really specific set of conditions needed to test, because XProtect sometimes does a _detection_ and _remediation_ without _writing a report file_. Phew, thank you @tutasla .

On a side note: if we did want to catch XProtect _detections_ rather than the existence of its _reports_, there is a new way to [get XProtect events in macOS Ventura 13.x, using the EndpointSecurity framework](https://developer.apple.com/documentation/endpointsecurity/es_event_xp_malware_detected_t). The downside: osquery would need to be monitoring for this event at the time it happened. That is a slightly different use-case than being able to pick up recent reports from the filesystem.

**Closed by mike-myers-tob** 2023-06-16 06:09 UTC
Labels: virtual tables, macOS, macOS Catalina

**Comment by nonpunctual** [comment] 2024-01-20 03:09
I wonder if you could consider reopening this under the assumption that an admin / user might not necessarily want an actual Xprotect remediation (which frankly would be hard to catch, dynamic & almost never useful for reporting) & instead might want data like this (i.e., what is the current Xprotect version, is it correct, compliant? etc.):

```
% silnite
{
    ASSecstatus =     (
        "Controller:",
        "      Model Identifier: Mac14,10",
        "      Firmware Version: iBoot-10151.61.4",
        "      Boot UUID: 3663C2C1-3CF8-4305-B454-365C2A3BD28E",
        "      Boot Policy:  ",
        "        Secure Boot: Full Security",
        "        System Integrity Protection: Enabled",
        "        Signed System Volume: Enabled",
        "        Kernel CTRR: Enabled",
        "        Boot Arguments Filtering: Enabled",
        "        Allow All Kernel Extensions: No",
        "        User Approved Privileged MDM Operations: No",
        "        DEP Approved Privileged MDM Operations: Yes"
    );
    FileVault = 1;
    KEXTV = "19.0.0";
    MRTUpdate = "2023-12-14 21:25:22 +0000";
    MRTV = "1.93";
    MRTVer = "1.93";
    MacModel = "Mac14,10";
    TCCV = "150.19";
    XPremV = 123;
    XPro = 1;
    XProtectV = 2179;
    XpremUpdate = "2024-01-17 08:12:37 +0000";
    XpremVer = 123;
    XproUpdate = "2024-01-17 08:12:34 +0000";
    XproVer = 2179;
    iBootV = "10151.61.4";
    macOS = "Version 14.2.1 (Build 23C71)";
}
brock@Brocks-MacBook-Pro tmp % help silnite
zsh: command not found: help
brock@Brocks-MacBook-Pro tmp % silnite help
silnite 10 usage:
silnite h to show this usage information.
silnite to run minimal check, no update check, returning JSONised XML (= bmx).
silnite a to check all and check for updates, returning text,
    add x to return JSONised XML,
    or add j to return JSON.
silnite b to run minimal check and check for updates, returning text,
    add m to run no update check,
    add x to return JSONised XML,
    or add j to return JSON.
add u to any of these to check for and install all pending updates.
brock@Brocks-MacBook-Pro tmp % silnite a   
Mac model Mac14,10
iBoot version found 10151.61.4; expected 10151.61.4
🍏 iBoot firmware appears up to date.
Mac model Mac14,10
iBoot version found 10151.61.4; expected 10151.61.4
🍏 iBoot firmware appears up to date.
✅ XProtect 2179 should be 2179
✅ XProtect Remediator 123 should be 123
✅ MRT 1.93 should be 1.93
✅ TCC 150.19 should be 150.19
✅ KEXT 19.0.0 should be 19.0.0
Apple silicon Security:
	🍏 Secure Boot: Full Security
	🍏 System Integrity Protection: Enabled
	🍏 Signed System Volume: Enabled
	🍏 Kernel CTRR: Enabled
	🍏 Boot Arguments Filtering: Enabled
	🍏 Allow All Kernel Extensions: No
	User Approved Privileged MDM Operations: No
	DEP Approved Privileged MDM Operations: Yes
✅ XProtect assessments enabled
✅ FileVault is On.
No update available.
macOS Version 14.2.1 (Build 23C71)
	XProtectPlistConfigData 2024-01-17 08:12:34 +0000 : 2179
	XProtectPayloads 2024-01-17 08:12:37 +0000 : 123
	MRTConfigData 2023-12-14 21:25:22 +0000 : 1.93
```

**Comment by directionless** [comment] 2024-01-20 12:30
@nonpunctual As the name implies,  the `xprotect_reports` is a table displaying the reports, if any. I think you're asking if we can expose some additional metadata? I don't think it's appropriate to add that metadata to the `xprotect_reports` table, but it might be in another table. Or it might be reasonable to add something for it. I'm not sure which part of that output you're referring to.

**Comment by nonpunctual** [comment] 2024-01-21 17:14
The output in my comment is from Ecclectic Light's app silnite. What I am saying is that I don't know if there is a bug or not, but, it is clear from this thread that the osquery table perhaps never really did anything that useful, but, exposing Xprotect data which should include actual malware reports if there are any on the system like silnite does without having to install a separate binary for silnite would probabbly be close to what the original Xprotect osquery table intended to do. Thanks.

**Comment by nonpunctual** [comment] 2025-03-21 14:26
https://github.com/osquery/osquery/issues/8573
