### ISSUE TITLE
ELK stack integration with Osquery

### ISSUE THREAD

**Issue by bhuvaneswari01** [osquery/osquery#6861] opened 2020-12-29 04:42 UTC
I want to integrate ELK stack with osquery. Please let me know how to do?

**Comment by theopolis** [comment] 2020-12-29 15:57
This issue is a duplicate of #6862. @bhuvaneswari01, please do not open multiple issues for the same question or problem. I also see that you are asking the same questions in Slack, please be patient as people are trying to learn more about your problem and are asking you clarifying questions. Please do not ask the same question in multiple places as it makes it difficult to answer you.

**Closed by theopolis** 2020-12-29 15:57 UTC
Labels: duplicate
