### ISSUE TITLE
OSQuery failed to cmake on windows due to error The source directory "D:/OSQuery/src" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by spacelg** [osquery/osquery#5601] opened 2019-06-24 10:35 UTC
We (the MSVC++ team) do a nightly build of the latest OSQuery sources as a compiler "Real World Code" test. OSQuery failed to cmake on windows due to error The source directory "D:/OSQuery/src" does not appear to contain CMakeLists.txt. Could you please have a look at this issue? Thanks a lot!

Repro steps:
1. git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2. Open a  VS 2017 x64 command prompt and browse to D:\OSQuery
3. cd src
4. tools\make-win64-dev-env.bat
5. mkdir build\windows10 && pushd build\windows10
6. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\..

[log_cmake.log](https://github.com/osquery/osquery/files/3320377/log_cmake.log)

Failures:
[executing command] cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\.. 
CMake Error: The source directory "D:/OSQuery/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[command took 0 seconds]

**Comment by groob** [comment] 2019-06-24 13:52
Which branch of the git repo are you using?

**Comment by groob** [comment] 2019-06-24 14:02
This issue looks like a duplicate of https://github.com/osquery/osquery/issues/5586 ?

**Comment by spacelg** [comment] 2019-06-25 03:16
Thanks for your reply!

We used master branch and see https://github.com/facebook/osquery/commits/master for the checkin history.

Thanks,
Lin

**Comment by groob** [comment] 2019-06-25 04:00
When I made the comment I didn’t realize the experimental branch was fast forwarded on master. CMake will come back soon, the repo is going through some changes
https://github.com/osquery/osquery/issues/5588

**Comment by groob** [comment] 2019-06-27 15:00
I think this is resolved

**Comment by spacelg** [comment] 2019-07-02 07:26
Hi groob,

Thanks for your reply and information! 

We use latest reversion to build OsQuery.  It failed to execute 'cmake --build . --target shell --config Release -- /maxcpucount' due to MSBUILD : error MSB1009: Project file does not exist. At the same time, we looked at the cmake log which has some exceptions: 'Could not find the WIX packaging tools, either install it or if it's Already installed, please set the WIX_ROOT_FOLDER_PATH variable to the root Folder of the WIX installation' . And we found this issue can be first reproduced on master branch 9428788 reversion which is 'Add CMake support '. Could you please have a look at this issue? Thanks a lot!

Repro steps:
1.git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2.Open a VS 2017 x64 command prompt and browse to D:\OSQuery
3.cd src
4.tools\make-win64-dev-env.bat
5.mkdir build\windows10 && pushd build\windows10
6.cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ....
7.cmake --build . --target shell --config Release -- /maxcpucount

[log_cmake.log](https://github.com/osquery/osquery/files/3348794/log_cmake.log)

[log_build_1.log](https://github.com/osquery/osquery/files/3348792/log_build_1.log)

Failures:
cmake --build . --target shell --config Release -- /maxcpucount  log:
[executing command] cmake --build . --target shell --config Release -- /maxcpucount 
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: shell.vcxproj
[command took 0 seconds] 

cmake log:
[executing command] cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\.. 
-- The C compiler identification is MSVC 19.23.27901.96
-- The CXX compiler identification is MSVC 19.23.27901.96
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.14.26428/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: 
-- Shared libraries: OFF
-- Found Python2: C:/tools/Python2/python.exe (found version "2.7.13") found components:  Interpreter 
-- Found Python3: C:/tools/Python3-amd64/python.exe (found version "3.7.3") found components:  Interpreter 
CMake Warning at cmake/packaging.cmake:111 (message):
  Could not find the WIX packaging tools, either install it or if it's
  already installed, please set the WIX_ROOT_FOLDER_PATH variable to the root
  folder of the WIX installation.
Call Stack (most recent call first):
  cmake/packaging.cmake:42 (findPackagingTool)
  CMakeLists.txt:50 (identifyPackagingSystem)
  CMakeLists.txt:56 (main)


-- Configuring done
-- Generating done
-- Build files have been written to: D:/OSQuery/src/build/windows10
[command took 23 seconds]

**Comment by QuellaZhang** [comment] 2019-07-09 06:19
@groob Any idea of the following error or new build steps? Thanks a lot.

errro info:
[executing command] cmake --build . --target shell --config Release -- /maxcpucount 
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: shell.vcxproj
[command took 1 seconds]

**Comment by Smjert** [comment] 2019-07-20 22:28
@spacelg: the warning on WIX is just a warning, is non fatal, it won't abort the cmake configuration or build.

@spacelg, @QuellaZhang: as the error is saying there's no `shell` target/project anymore, since we merged experimental into master now the target/project you need to build osqueryd is called `osqueryd`.
But unless you've enabled tests and don't want to build them, you don't necessarily need to specify the target to build.

Also please follow the [BUILD.md](https://github.com/osquery/osquery/blob/master/BUILD.md) document on how to build with CMake and don't use the powershell script.

**Comment by Smjert** [comment] 2019-07-30 12:58
I'll close it again, I think it was just a matter of following the new guide.
I would suggest opening a new issue if there are any problems with it.

**Closed by Smjert** 2019-07-30 12:58 UTC
