### ISSUE TITLE
osquery shell sometimes returns the results in second querying

### ISSUE THREAD

**Issue by kemalbayar** [osquery/osquery#4175] opened 2018-03-08 08:34 UTC
the case showing in the picture repeats sometimes when using different queries 

![osqu](https://user-images.githubusercontent.com/33925821/37140835-1c671a46-22c4-11e8-82fc-2f99a8c2ae34.png)

**Comment by muffins** [comment] 2018-03-08 15:59
Can you give us more information when you're creating issues? Getting really vague problem statements makes it a bit difficult for us to triage what issue you might be having. Can you throw us what version of osquery you're running and on which platform and version? Based off of you're output this is looking like Windows but I can't repro this, what version of Windows and osquery are you running?

**Comment by kemalbayar** [comment] 2018-03-09 08:19
osquery version: 2.11.2
build_platform:windows
build_distro:windows10 (but it's running on windows server 2016! / virtual environment)
and...
![image](https://user-images.githubusercontent.com/33925821/37197394-b020a65e-238b-11e8-9300-705b4f3d107a.png)

**Comment by muffins** [comment] 2018-03-09 17:35
@kemalbayar are you able to repro this issue with any other tables? Or is this only with the `etc_services` table?

**Comment by kemalbayar** [comment] 2018-03-12 07:00
it happens not only etc_services table but also happened with a few table (i don't remember the names)

**Comment by muffins** [comment] 2018-03-14 05:08
Ok, this will be rather difficult to diagnose and triage if we can’t reproduce, so definitely let us know if you figure out which other tables this happens on. In the mean time we will see if anyone else has experienced this and see if we can reproduce ourselves.

**Comment by Smjert** [comment] 2019-12-29 16:23
While I wasn't able to reproduce it, it's most likely related to https://github.com/osquery/osquery/issues/5661, since the table implementation does use the async version of readFile.

**Comment by Smjert** [comment] 2020-10-25 15:54
I'm going to close this issue since I wasn't able to reproduce in the past and the readFile issue has been solved.
Please test with latest osquery (4.5.1) and if it's still present, reopen this.

**Closed by Smjert** 2020-10-25 15:54 UTC
Labels: Windows, bug, virtual tables
