### ISSUE TITLE
osqueryi not returning output for routes table on the CLI

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [osquery/osquery#6700] opened 2020-10-06 17:18 UTC
Hi All,

I tried executing the `select * from routes` in **osquery** cli and I am not getting any responses and never returned any output of the query. I tried the same command in other environment which has same OS and version and I am able to get response.

**Environment details,**
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID_LIKE=debian

`osqueryi --json "select * from routes";`

Version of osquery: **4.5.0**

I tried checking few threads and I could see the same issue happened in OS centos and still in open. I couldn't solve the issue and please let me know how to solve this problem

https://github.com/osquery/osquery/issues/6636
https://github.com/osquery/osquery/issues/2591

Regards,
Ganeshbabu R

**Comment by theopolis** [comment] 2021-02-21 21:02
This is a duplicate of https://github.com/osquery/osquery/issues/5276 (I am trying to condense duplicated bug reports).

**Closed by theopolis** 2021-02-21 21:02 UTC
Labels: Linux, triage, virtual tables
