### ISSUE TITLE
changing query resets the counter in differential logs. 

### ISSUE THREAD

**Issue by groob** [osquery/osquery#5299] opened 2018-11-16 17:51 UTC
# Bug report

### What operating system and version are you using?

```
 version = 10.14.1
   build = 18B75
platform = darwin
```

### What version of osquery are you using?
       version = 3.3.0

If I schedule a new query into a pack, the differential results will include a counter field, which is the count of executions of that query. It should be a monotonically increasing number. However I'm seeing an edge case where the counter resets if the query fields change (repro below). 
IMO this is a bug, counter should persist as long as the name of the query in the pack is the same. 

Config at start:
```
{
  "options": {
    "logger_event_type": false,
    "utc": "true"
  },
  "schedule": {
    "some_pack": {
      "query": "SELECT 1, unix_time from time",
      "interval": 1
    }
  }
}
```

logs:

```
{
  "diffResults": {
    "removed": [
      {
        "1": "1",
        "unix_time": "1542388062"
      }
    ],
    "added": [
      {
        "1": "1",
        "unix_time": "1542388063"
      }
    ]
  },
  "name": "some_pack",
  "hostIdentifier": "kl.groob.io",
  "calendarTime": "Fri Nov 16 17:07:43 2018 UTC",
  "unixTime": 1542388063,
  "epoch": 0,
  "counter": 155
}
```

Then, i change the config

```
{
  "options": {
    "logger_event_type": false,
    "utc": "true"
  },
  "schedule": {
    "some_pack": {
      "query": "SELECT 2, unix_time from time",
      "interval": 1
    }
  }
}
```

And, my logs:

```
{
  "diffResults": {
    "removed": [
      {
        "1": "1",
        "unix_time": "1542388063"
      }
    ],
    "added": [
      {
        "2": "2",
        "unix_time": "1542388073"
      }
    ]
  },
  "name": "some_pack",
  "hostIdentifier": "kl.groob.io",
  "calendarTime": "Fri Nov 16 17:07:53 2018 UTC",
  "unixTime": 1542388073,
  "epoch": 0,
  "counter": 0
}
I1116 12:07:54.314043 234246144 scheduler.cpp:97] Executing scheduled query some_pack: SELECT 2, unix_time from time
{
  "diffResults": {
    "removed": [
      {
        "2": "2",
        "unix_time": "1542388073"
      }
    ],
    "added": [
      {
        "2": "2",
        "unix_time": "1542388075"
      }
    ]
  },
  "name": "some_pack",
  "hostIdentifier": "kl.groob.io",
  "calendarTime": "Fri Nov 16 17:07:55 2018 UTC",
  "unixTime": 1542388075,
  "epoch": 0,
  "counter": 1
}
```

**Comment by obelisk** [comment] 2018-11-19 12:55
I _think_ this is intended behaviour because the counter should increase every time the query is run, if the query changes, then the number of times _that query_ has run is 0. At least this is my understanding. Why is the counter resetting an issue, I feel it resetting provides more information than if it didn't.

**Comment by groob** [comment] 2018-11-19 13:06
@obelisk it’s an issue if you’re looking to use `epoch,counter` of a query as values to store/retrieve/range over results.

**Comment by directionless** [comment] 2024-02-18 14:37
I'm not sure what correct is -- if you change SQL, then it might invalidate your diff results. I also can't remember what our current behavior is. But I'm going to close this issue in spring cleaning

**Closed by directionless** 2024-02-18 14:37 UTC
Labels: triage
