### ISSUE TITLE
File has unexpected size

### ISSUE THREAD

**Issue by carmo-evan** [osquery/osquery#8466] opened 2024-11-05 18:55 UTC
# Bug report

### What operating system and version are you using?

```
Debian (insert version here, e.g., Debian 10 Buster or Debian 11 Bullseye)
```

### What version of osquery are you using?

```
(osqueryi --line "SELECT version from osquery_info;" output here)
```

### What steps did you take to reproduce the issue?
1. Attempted to update or install a package using `apt-get` or `apt`.
2. Ran the command to fetch package lists, e.g., `apt-get update`.

### What did you expect to see?
I expected the package lists to download successfully without errors.

### What did you see instead?
I encountered the error message:

```
E: Failed to fetch https://pkg.osquery.io/deb/dists/deb/main/binary-amd64/Packages  File has unexpected size (22693 != 23098). Mirror sync in progress? [IP: 104.21.44.46 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by michael-myers** [comment] 2024-12-17 07:01
That error message is being emitted by the package manager `apt`, not osquery.  The discussion here might be helpful: https://askubuntu.com/questions/1147254/apt-update-fails-at-chrome-stable-main-file-has-unexpected-size-1103-1104 but if you think the issue is with osquery, please provide the osquery command and osquery output.

I am closing the issue, but you are welcome to reopen it if you still have the issue and can provide the context for it being an osquery problem.

**Closed by michael-myers** 2024-12-17 07:01 UTC
