### ISSUE TITLE
database in a state where osquery is permanently at 100% CPU

### ISSUE THREAD

**Issue by mikegeoffrey** [osquery/osquery#5425] opened 2019-02-07 20:10 UTC
# Bug report

### What operating system and version are you using?

```
version = CentOS Linux release 7.6.1810 (Core)
  build = 
platform = rhel
```

### What version of osquery are you using?

``version = 3.3.1``

### What steps did you take to reproduce the issue?

Started osqueryd like so:

`osqueryd --config_path /etc/osquery/osquery.conf --ephemeral --database_path /tmp/osquery.db --verbose --audit_allow_config=true --disable_audit=false --audit_persist=true --audit_allow_sockets --logger_plugin=filesystem --logger_path /tmp/  --disable_events=false`

and events are logged, cpu usage is minimal, it's working as expected.

Stop the above command and restarted it but pointing at the database path which osquery has been using for a few months now and which results in 100% CPU usage and the watchodg continuously stopping the worker:

Started like this:

`osqueryd --config_path /etc/osquery/osquery.conf --ephemeral --database_path /var/osquery/osquery.db --verbose --audit_allow_config=true --disable_audit=false --audit_persist=true --audit_allow_sockets --logger_plugin=filesystem --logger_path /tmp/  --disable_events=false`

and this is the output, which just repeats endlessly with 1 core being fully utilised:

```
I0207 19:49:31.337944 10162 init.cpp:416] osquery initialized [version=3.3.1]
I0207 19:49:31.338062 10162 extensions.cpp:343] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0207 19:49:31.338722 10163 watcher.cpp:583] osqueryd watcher (10162) executing worker (10164)
I0207 19:49:31.345352 10164 init.cpp:413] osquery worker initialized [watcher=10162]
I0207 19:49:31.345492 10164 rocksdb.cpp:134] Opening RocksDB handle: /var/osquery/osquery.db
I0207 19:49:31.411991 10164 database.cpp:563] Checking database version for migration
I0207 19:49:31.412817 10164 auto_constructed_tables.cpp:86] Removing stale ATC entries
I0207 19:49:31.412907 10171 interface.cpp:265] Extension manager service starting: /var/osquery/osquery.em
I0207 19:49:31.415494 10164 killswitch.cpp:60] osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0207 19:49:31.415791 10164 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configuration
I0207 19:50:15.410164 10164 events.cpp:1116] Error registering subscriber: process_file_events: Subscriber disabled via configuration
I0207 19:50:30.146428 10164 events.cpp:1116] Error registering subscriber: selinux_events: Subscriber disabled via configuration
W0207 19:50:31.351933 10163 watcher.cpp:331] osqueryd worker (10164) stopping: Maximum sustainable CPU utilization limit exceeded: 60
I0207 19:50:35.351994 10164 init.cpp:157] Cannot stop event publisher threads or services
I0207 19:50:35.554739 10163 watcher.cpp:583] osqueryd watcher (10162) executing worker (11171)
I0207 19:50:35.564723 11171 init.cpp:413] osquery worker initialized [watcher=10162]
I0207 19:50:35.564874 11171 rocksdb.cpp:134] Opening RocksDB handle: /var/osquery/osquery.db
I0207 19:50:35.643265 11171 database.cpp:563] Checking database version for migration
I0207 19:50:35.643812 11171 auto_constructed_tables.cpp:86] Removing stale ATC entries
I0207 19:50:35.643908 11178 interface.cpp:265] Extension manager service starting: /var/osquery/osquery.em
I0207 19:50:35.645887 11171 killswitch.cpp:60] osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0207 19:50:35.646138 11171 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configuration
W0207 19:50:47.557904 10163 watcher.cpp:331] osqueryd worker (11171) stopping: Maximum sustainable CPU utilization limit exceeded: 12
I0207 19:50:51.557945 11171 init.cpp:157] Cannot stop event publisher threads or services
I0207 19:50:51.760653 10163 watcher.cpp:583] osqueryd watcher (10162) executing worker (11345)
I0207 19:50:51.770324 11345 init.cpp:413] osquery worker initialized [watcher=10162]
I0207 19:50:51.770467 11345 rocksdb.cpp:134] Opening RocksDB handle: /var/osquery/osquery.db
I0207 19:50:51.845989 11345 database.cpp:563] Checking database version for migration
I0207 19:50:51.846524 11345 auto_constructed_tables.cpp:86] Removing stale ATC entries
I0207 19:50:51.846588 11352 interface.cpp:265] Extension manager service starting: /var/osquery/osquery.em
I0207 19:50:51.848565 11345 killswitch.cpp:60] osquery::Killswitch::IsEnabledError 1 (Cannot call registry item: )
I0207 19:50:51.848794 11345 events.cpp:863] Event publisher not enabled: syslog: Publisher disabled via configuration
W0207 19:51:03.763845 10163 watcher.cpp:331] osqueryd worker (11345) stopping: Maximum sustainable CPU utilization limit exceeded: 12
```

### What did you expect to see?

As above.

### What did you see instead?

As above.

**Comment by mikegeoffrey** [comment] 2019-02-08 10:37
Additionally, below is a file listing of where the osquery database files are, and attached is strace output when attaching to a worker process very soon after it spawned:

[strace.log](https://github.com/facebook/osquery/files/2844687/strace.log)

total 44M
-rw-r--r-- 1 root root    0 Nov 14 13:16 LOCK
-rw-r--r-- 1 root root   37 Nov 14 13:16 IDENTITY
-rw-r--r-- 1 root root 1.8M Nov 27 14:56 030051.sst
-rw-r--r-- 1 root root 2.1M Nov 27 14:56 030052.sst
-rw-r--r-- 1 root root 719K Nov 27 14:56 030053.sst
-rw-r--r-- 1 root root 4.9M Jan 21 21:37 156421.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156422.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156423.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156424.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156425.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156426.sst
-rw-r--r-- 1 root root 1.1M Jan 21 21:37 156428.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156429.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156430.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156431.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156432.sst
-rw-r--r-- 1 root root 2.1M Jan 21 21:37 156433.sst
-rw-r--r-- 1 root root 4.9M Jan 21 21:37 156434.sst
-rw-r--r-- 1 root root 2.4M Jan 22 16:35 158250.sst
-rw-r--r-- 1 root root 1.3M Jan 22 16:35 158251.sst
-rw-r--r-- 1 root root  62K Jan 22 16:40 158256.sst
-rw-r--r-- 1 root root  61K Jan 22 16:45 158263.sst
-rw-r--r-- 1 root root  86K Jan 22 16:50 158271.sst
-rw-r--r-- 1 root root  49K Jan 29 12:40 266757.sst
-rw-r--r-- 1 root root  962 Jan 29 13:17 267168.sst
-rw-r--r-- 1 root root  955 Jan 29 13:20 267199.sst
-rw-r--r-- 1 root root 1.6K Jan 29 13:20 267201.sst
-rw-r--r-- 1 root root   16 Feb  8 11:36 CURRENT
-rw-r--r-- 1 root root 3.5K Feb  8 11:36 MANIFEST-424139
-rw-r--r-- 1 root root    0 Feb  8 11:36 424140.log
drwx------ 2 root root 4.0K Feb  8 11:36 .
drwxrwxr-x 3 root root 4.0K Feb  8 11:36 ..

**Comment by mikegeoffrey** [comment] 2019-02-08 13:35
A workaround is to add `--watchdog_delay=120` to /etc/osquery/osquery.flags. Why osquery takes longer than 60 seconds, the watchdog timeout default, to open such a small database I don't know.

**Comment by fmanco** [comment] 2019-02-08 15:46
To clarify, with the watchdog delay flag, after some time does the CPU usage drop or does it keep at 100%?

**Comment by mikegeoffrey** [comment] 2019-02-08 16:10
It will drop and things run as normal. However after an hour or so it was back up to 100% and not producing any logs, and stuck in the cycle.  This line appeared 18 times during the period when it started off fine but ramped up to 100%, with the delay flag.

`Feb  8 16:40:01 osqueryd[14433]: severity=0 location=database.cpp:134 message=Resetting the database plugin: rocksdb`

**Comment by mikegeoffrey** [comment] 2019-02-08 16:42
I've run sst_dump on the files and there about 38k of these lines across the 20 .sst files.
`data.auditeventpublisher.process_events.0003350252' seq:6482196, type:0 =>`
Which can be found in the strace.log attached above.
There are also events from beginning of January in some of the files.

**Comment by erickellerek1** [comment] 2020-03-15 15:59
This still affects the latest version `4.2.0-1.linux` on Ubuntu 18.04.
logs are full of:
```
Mar 12 13:03:26 foobar osqueryd[1061]: osqueryd worker (18739) stopping: Maximum sustainable CPU utilization limit exceeded: 12
Mar 12 13:03:26 foobar osqueryd[1061]: W0312 13:03:26.534276  1169 watcher.cpp:331] osqueryd worker (18739) stopping: Maximum sustainable CPU utilization limit exceeded: 12
Mar 12 13:03:27 foobar osqueryd[1061]: I0312 13:03:27.061452 18753 database.cpp:570] Checking database version for migration
Mar 12 13:03:27 foobar osqueryd[1061]: W0312 13:03:27.094579 18753 options.cpp:91] Cannot set unknown or invalid flag: enable_monitor
Mar 12 13:03:27 foobar osqueryd[1061]: W0312 13:03:27.094651 18753 options.cpp:91] Cannot set unknown or invalid flag: log_result_events
```
any news about this?

**Comment by theopolis** [comment] 2020-03-15 20:40
Are you able to share the database with me (privately) on Slack?

**Comment by erickellerek1** [comment] 2020-03-16 17:02
Unfortunately I just delete the `/var/osquery/osquery.db/*` and restarted the service again, this is a spontaneous workaround.

I will be able to publish the files privately of course. In the meantime I am at `--watchdog_delay=240` and as @mikegeoffrey mentioned this is just temporary.

**Comment by Smjert** [comment] 2020-03-16 17:15
@erickellerek1 If you can, try to monitor how many events you are receiving.
Also how osquery is configured?
Specifically, which events are you taking and how `events_expiry` is set up, if it is?

Do you ever see osquery/RocksDB complaining about write stalls or hitting the 50k event limit?

**Comment by erickellerek1** [comment] 2020-03-16 20:27
the osquery events gave this:
```
osquery>  select * from osquery_events;
+---------------------+---------------------+------------+---------------+--------+-----------+--------+
| name                | publisher           | type       | subscriptions | events | refreshes | active |
+---------------------+---------------------+------------+---------------+--------+-----------+--------+
| auditeventpublisher | auditeventpublisher | publisher  | 3             | 0      | 1         | 1      |
| inotify             | inotify             | publisher  | 0             | 0      | 1         | 1      |
| syslog              | syslog              | publisher  | 1             | 0      | 0         | 0      |
| udev                | udev                | publisher  | 1             | 0      | 1         | 1      |
| file_events         | inotify             | subscriber | 0             | 0      | 0         | 1      |
| hardware_events     | udev                | subscriber | 1             | 0      | 0         | 1      |
| process_events      | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| process_file_events | auditeventpublisher | subscriber | 0             | 0      | 0         | 0      |
| selinux_events      | auditeventpublisher | subscriber | 0             | 0      | 0         | 0      |
| socket_events       | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| syslog_events       | syslog              | subscriber | 1             | 0      | 0         | 1      |
| user_events         | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| yara_events         | inotify             | subscriber | 0             | 0      | 0         | 1      |
+---------------------+---------------------+------------+---------------+--------+-----------+--------+
```
I will monitor when the failure occurs again.

here are the configuration:

```
cat /etc/osquery/osquery.conf                                                                                                                                               
{
    "decorators": {
        "load": [
            "SELECT uuid AS host_uuid FROM system_info;", 
            "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
        ]
    }, 
    "options": {
        "audit_allow_config": "true", 
        "audit_allow_sockets": "true", 
        "config_plugin": "filesystem", 
        "disable_audit": "false", 
        "disable_events": "false", 
        "disable_logging": "false", 
        "enable_monitor": "true", 
        "enable_syslog": "true", 
        "events_expiry": "3600", 
        "host_identifier": "hostname", 
        "log_result_events": "true", 
        "logger_path": "/var/log/osquery", 
        "logger_plugin": "filesystem", 
        "schedule_default_interval": "3600", 
        "schedule_splay_percent": "10", 
        "verbose": "false", 
        "worker_threads": "2"
    }, 
    "packs": {
        "*": "/etc/osquery/rlc_*.conf"
    }
}
```

```
cat osquery.flags                                                                                                                                                
--watchdog_delay=240
```

```
cat debian.conf                                                                                                                                        
{
    "queries": {
        "apt_sources": {
            "description": "Current list of APT repositories or software channels.", 
            "interval": 7200, 
            "platform": "linux", 
            "query": "SELECT * FROM apt_sources;", 
            "version": "1.0.0"
        }, 
        "deb_packages": {
            "description": "The installed DEB package database.", 
            "interval": 7200, 
            "platform": "linux", 
            "query": "SELECT * FROM deb_packages;", 
            "version": "1.0.0"
        }
    }
}
```

```
cat hardware.conf                                                                                                                                      
{
    "queries": {
        "kernel_info": {
            "description": "Basic active kernel information.", 
            "interval": 7200, 
            "platform": "all", 
            "query": "SELECT * FROM kernel_info;", 
            "snapshot": "True", 
            "version": "1.0.0"
        }
    }
}%
```

```
cat network.conf                                                                                                                                       
{
    "queries": {
        "dns_resolvers": {
            "description": "Resolvers used by this host.", 
            "interval": 600, 
            "platform": "linux", 
            "query": "SELECT * FROM dns_resolvers;", 
            "version": "1.0.0"
        }, 
        "etc_hosts": {
            "description": "Line-parsed /etc/hosts.", 
            "interval": 3600, 
            "platform": "all", 
            "query": "SELECT * FROM etc_hosts;", 
            "version": "1.0.0"
        }, 
        "interface_addresses": {
            "description": "Network interfaces and relevant metadata.", 
            "interval": 600, 
            "platform": "all", 
            "query": "SELECT interface_addresses.interface, address, mask, mac FROM interface_addresses, interface_details WHERE interface_addresses.interface = interface_details.interface AND interface_addresses.interface != 'lo';", 
            "version": "1.0.0"
        }, 
        "routes": {
            "description": "The active route table for the host system.", 
            "interval": 600, 
            "platform": "all", 
            "query": "SELECT * FROM routes WHERE interface != 'lo';", 
            "version": "1.0.0"
        }
    }
}
```

```
cat system.conf                                                                                                                                        
{
    "queries": {
        "load_average": {
            "description": "Displays information about the system wide load averages.", 
            "interval": 600, 
            "platform": "linux", 
            "query": "SELECT * FROM load_average;", 
            "version": "1.0.0"
        }, 
        "memory_info": {
            "description": "Main memory information in bytes.", 
            "interval": 600, 
            "platform": "linux", 
            "query": "SELECT * FROM memory_info;", 
            "version": "1.0.0"
        }, 
        "os_version": {
            "description": "A single row containing the operating system name and version.", 
            "interval": 7200, 
            "platform": "all", 
            "query": "SELECT * FROM os_version;", 
            "snapshot": "True", 
            "version": "1.0.0"
        }, 
        "processes": {
            "description": "All running processes on the host system.", 
            "interval": 600, 
            "platform": "all", 
            "query": "SELECT * FROM processes;", 
            "version": "1.0.0"
        }, 
        "system_info": {
            "description": "System information for identification.", 
            "interval": 7200, 
            "platform": "all", 
            "query": "SELECT * FROM system_info;", 
            "snapshot": "True", 
            "version": "1.0.0"
        }, 
        "time": {
            "description": "Track current date and time in the system.", 
            "interval": 7200, 
            "platform": "all", 
            "query": "SELECT timezone, local_timezone, iso_8601 FROM time;", 
            "snapshot": "True", 
            "version": "1.0.0"
        }
    }
}
```

nothing in the logs matches `osquery/RocksDB` neither in the journalctl

**Comment by Smjert** [comment] 2020-03-16 21:01
@erickellerek1 Thanks for those configs!
Sorry I have been a bit vague with the logs, I meant, do you see logs like:
```
Expiring events for subscriber: process_events (overflowed limit 50000)
```
or for other subscribers?

At the same time do you see (numbers may change):
```
[queries] Stalling writes because we have 15 immutable memtables [...]
```

**Comment by erickellerek1** [comment] 2020-03-17 15:51
I maybe have some other user who is affected by this issue and would be able to send you some tarball with the database files for further debuging.
concerning the events, in the `journalctl -u osqueryd -f` is writting a lot of these events...
```
...
Mar 17 16:39:09 foobar osqueryd[25313]: W0317 16:39:09.818588 25360 events.cpp:311] Expiring events for subscriber: socket_events (overflowed limit 50000)
...
```
I can export the journalctl logs if you need...
Still the 100% CPU is not reproducible :(

I will perform some watch and trigger of osqueryi to isolate the values of the SQL selection.

osquery> select * from osquery_events;
+---------------------+---------------------+------------+---------------+--------+-----------+--------+
| name                | publisher           | type       | subscriptions | events | refreshes | active |
+---------------------+---------------------+------------+---------------+--------+-----------+--------+
| auditeventpublisher | auditeventpublisher | publisher  | 3             | 0      | 24        | 1      |
| inotify             | inotify             | publisher  | 0             | 0      | 24        | 1      |
| syslog              | syslog              | publisher  | 1             | 0      | 0         | 0      |
| udev                | udev                | publisher  | 1             | 0      | 24        | 1      |
| file_events         | inotify             | subscriber | 0             | 0      | 0         | 1      |
| hardware_events     | udev                | subscriber | 1             | 0      | 0         | 1      |
| process_events      | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| process_file_events | auditeventpublisher | subscriber | 0             | 0      | 0         | 0      |
| selinux_events      | auditeventpublisher | subscriber | 0             | 0      | 0         | 0      |
| socket_events       | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| syslog_events       | syslog              | subscriber | 1             | 0      | 0         | 1      |
| user_events         | auditeventpublisher | subscriber | 1             | 0      | 0         | 1      |
| yara_events         | inotify             | subscriber | 0             | 0      | 0         | 1      |
+---------------------+---------------------+------------+---------------+--------+-----------+--------+

was the latest state

**Comment by Smjert** [comment] 2020-03-17 20:29
@erickellerek1
Regarding the high CPU usage, a reason could also be that if the DB has been kept through different osquery upgrades, DB migration might have failed, so you might've had some dead keys in there that were still scanned, and so they would create performance overhead.
So if with the new DB this doesn't happen, that's most likely the reason.

I also see that you have the overflow limit message and this suggests me that something in the configuration or in how events are currently used is not what's expected.

With events there are several things to consider and necessary to know:
1) What kind of information you want to get out of them? A history of what happened? A more immediate warning about something that's happening? (there are obviously more cases in between, but this are the two extremes, I think).
2) Events are collected and kept in RocksDB forever if you never query the tables that have them.
3) Events are expired when you query the table that contains them (as stated above); which ones are expired is chosen by the `events_expiry` setting.
By default this setting is 3600, which means 1h. So when you query a table, any event that is older than 1h will be expired/dropped. This permits the table to be queried multiple times for the same results to be returned.
There's a special value, which is `1`, which will drop all events as soon as you query them.
4) There's a default limit on the number of events stored in RocksDB which is 50.000. This can be controlled with the `events_max` flag.
This means that if the events stored in RocksDB go beyond that limit, the DB will start expiring the oldest records. Doing this has a cost too.

So in general, try to enable only what you need, try to query often and keep expiration times low or 1, do not keep default values and tune to your usage to avoid hitting the limit.
You can of course increase the limit if you think that the hardware osquery runs on can deal with it and it will not trigger the watchdog, or if you need to catch spikes.
If you don't need to query often and you don't need to keep a history of what happens on the machine, maybe events are not the right source of information to use.

**Comment by erickellerek1** [comment] 2020-03-18 18:21
great thanks for the details.
Concerning the Database is there a way to check it's consistency or failed migration?
I will review our configuration and check if the events are the right source of information to use.

**Comment by directionless** [comment] 2020-09-30 03:03
Do you think this would have been fixed by https://github.com/osquery/osquery/pull/6606 ?

**Comment by theopolis** [comment] 2020-09-30 15:19
Yes, and I think we can close this until we confirm similar poor experiences on version 4.4.0 or 4.5.0. There have been too many fixes and improvements to try to root cause a problem on 3.x (sorry about never being definitive here).

Please feel free to re-open if this experience is still happening on the 4.x releases.

**Closed by theopolis** 2020-09-30 15:19 UTC
Labels: database, triage
