### ISSUE TITLE
Windows Extension goes away if  "select * from pipes" query is issued.

### ISSUE THREAD

**Issue by preetpoly** [osquery/osquery#4280] opened 2018-04-12 08:40 UTC
Details are as follows - 
 1) Issue query "select * from pipes" from osquery shell or via scheduled queries.

2) This causes Extension Service responsible for communication with Extensions via pipe (\\.\pipe\shell.em) to exit.

3) Extension Watcher detects that shell.em no longer exists and throws following message 
I0412 01:20:24.826747  6708 extensions.cpp:208] Extension watcher ending: osquery core has gone away
and extension exits.

4) Osquery core is not able to restart extension again as it can not find  pipe -  \\.\pipe\shell.em

Possible Root cause is as follows -

Select * from pipes query logic opens all pipes present on the system (including shell.em) and reports its status in the query result. 
Opening a client pipe handle connects to the server pipe instance (which created shell.em pipe), which is served by thrift server for named pipes. Thrift server creates a thread for each client connection and if a client disconnects before thrift server offloads the new connection to a thread, an exception is thrown and the thrift server exits, resulting in a sequence of events -> shell.em is deleted-> extension exits->osquery cannot start extension again.

Though we observed this issue with our custom extension but issue can be reproduced with any extension.

Osquery Version - 2.11.2

**Comment by muffins** [comment] 2018-04-12 18:01
[Wop wop](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/pipes.cpp#L42). Nice triage! Looks like we do indeed connect the named pipe, and thus cause the breakage :)

**Comment by mike-myers-tob** [comment] 2020-11-17 17:52
Confirmed to still affect the latest osquery.

```
PS C:\Projects\osquery\build> .\osquery\RelWithDebInfo\osqueryi.exe --allow_unsafe --extension .\external\extension_trailofbits\RelWithDebInfo\trailofbits_osquery_extensions.ext.exe                    
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> select * from pipes;
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
| pid  | name                                                       | instances | max_instances | flags                             |
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
| 524  | InitShutdown                                               | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 620  | lsass                                                      | 6         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 604  | ntsvcs                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 604  | scerpc                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-26c-0                       |           |               |                                   |
|      | Winsock2\CatalogChangeListener-3a8-0                       |           |               |                                   |
| 936  | epmapper                                                   | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-20c-0                       |           |               |                                   |
| 980  | LSM_API_service                                            | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 1128 | atsvc                                                      | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 1272 | eventlog                                                   | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-4f8-0                       |           |               |                                   |
|      | Winsock2\CatalogChangeListener-468-0                       |           |               |                                   |
| 2396 | spoolss                                                    | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-95c-0                       |           |               |                                   |
| 2580 | wkssvc                                                     | 6         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 2984 | trkwks                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 3004 | W32TIME_ALT                                                | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | Winsock2\CatalogChangeListener-25c-0                       |           |               |                                   |
| 2904 | srvsvc                                                     | 4         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 3308 | ROUTER                                                     | 3         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 6464 | MsFteWds                                                   | 6         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 6464 | SearchTextHarvester                                        | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
|      | PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER                     |           |               |                                   |
| 6212 | vgauth-service                                             | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 2324 | PSHost.132491847859571903.2324.DefaultAppDomain.powershell | 1         | 1             | PIPE_CLIENT_END,PIPE_TYPE_MESSAGE |
| 8496 | shell.em                                                   | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
| 2680 | shell.em.30009                                             | 1         | 255           | PIPE_CLIENT_END,PIPE_TYPE_BYTE    |
|      | 1b90.1d6bd08c6c242ad-714.1d6bd08c659dd06                   |           |               |                                   |
+------+------------------------------------------------------------+-----------+---------------+-----------------------------------+
osquery> I1117 09:40:48.372915  6428 extensions.cpp:298] Extension watcher ending: osquery core has gone away
E1117 09:41:05.638562  4980 osquery_extension_group_main.cpp:36] Extension socket not available: \\.\pipe\shell.em

osquery> E1117 09:41:21.591673  6392 osquery_extension_group_main.cpp:36] Extension socket not available: \\.\pipe\shell.em
E1117 09:41:35.998015  1636 osquery_extension_group_main.cpp:36] Extension socket not available: \\.\pipe\shell.em
```

**Comment by mike-myers-tob** [comment] 2021-02-02 20:03
Known issue in Thrift, now fixed. Thanks @Smjert for noticing their fix. https://issues.apache.org/jira/browse/THRIFT-5078

@theopolis can you do your Thrift patch generation magic again? Need these changes https://github.com/apache/thrift/pull/1964/files

**Closed** 2021-02-03 13:05 UTC
Labels: Windows, bug, extensions, medium
