### ISSUE TITLE
syslog table not populated in 3.2.6

### ISSUE THREAD

**Issue by keithshum** [osquery/osquery#4810] opened 2018-08-07 03:52 UTC
### What versions?

osquery_version = 3.2.6
     os_version = Red Hat Enterprise Linux Server release 7.2 (Maipo)
       os_build =
    os_platform = rhel

### What have you already tried?
Followed steps at https://github.com/facebook/osquery/issues/1964 and I can cat the pipe file to see the test message. 

### What did you expect to see?
I expected to see the log entries from the output of "select * from syslog".

### What did you see instead?
No data display.

### What's working?
I consulted w/ @zwass at osquery slack channel and he suggested to try 2.11.2. I deployed it on the same platform and working well. I can see the data right the way.

**Comment by zwass** [comment] 2018-08-07 17:53
@clong thank you for chiming in here. That seems very likely related. Do we expect this to be fixed in 3.3.0 then?

**Comment by keithshum** [comment] 2018-08-08 00:51
No, unfortunately. Still no output.

**Comment by yuzukiseo** [comment] 2018-08-08 04:31
I have same issue - osquery installed on the server with:

- CentOS 7
- Version 3.2.6

Tried to remove the osquery.db directory and still same.

**Comment by hughneale** [comment] 2018-08-13 19:48
Just to provide a bit of an update.

When debugging osqueryi. The `syslog.cpp` is polling the pipe without problem.

https://github.com/facebook/osquery/blob/master/osquery/events/linux/syslog.cpp#L161

However, `readStream_.rdbuf()->in_avail()` keeps returning 0, indicating there is no data in the pipe even when there is. Going through the PRs since 2.11.2 to try and work out whats changed.

**Comment by hughneale** [comment] 2018-08-27 07:29
Sorry meant to update this thread days ago. The commit [c4c5385253f7c86d3e84667b8207abaf0d93478a](https://github.com/facebook/osquery/commit/c4c5385253f7c86d3e84667b8207abaf0d93478a) seems to be where the issue has occurred. 

There was a bulk upgrade of a whole load of dependancies. Wondering if the upgrade of llvm from 4.0.0 to 5.0.1 is the cause? Though i've not seen anything in there issue trackers. 

@theopolis able to shine any light on this?

**Comment by mproffitt** [comment] 2018-09-16 11:28
Testing on ubuntu 18.04, this issue is also apparent and comes down to `readStream_.rdbuf()->in_avail()` always returning 0 even when there is data in the pipe. This seems to be fairly common behaviour on some implementations as `in_avail` calls down to `showmanyc` which returns 0 to indicate there is no information available but subsequent reads may reveal data. 

By changing:
```
    if (readStream_.rdbuf()->in_avail() == 0) {
      return Status(0, "OK");
    }
    std::string line;
    std::getline(readStream_, line);
```
to become
```
    std::string line;
    std::getline(readStream_, line);
    if (line.length() == 0) {
      return Status(0, "OK");
    }
```
the syslog tables are then populated; however shutting down the client seems to take longer and from my own testing, will hang indefinitely unless `readStream_.close()` is added into the `tearDown` above `unlockPipe`

As an aside, data will only flow into the pipe if rsyslog is restarted *after* osquery has obtained its lock. Likewise, once osquery is shutdown, rsyslog also seems to lose the capability to write into that pipe without being restarted. I haven't tested this with syslog-ng although I'd anticipate the same behaviour.

I would presume this aside to be less of an issue when the daemon is running but if testing using only `osqueryi` it's worth bearing in mind that the syslog service needs restarting after osqueryi has been `initialised`.

**Comment by aallawala** [comment] 2019-06-11 19:49
would anyone happen to know if this has been addressed and merged? I'm seeing something similar occur on my end in osquery v3.3.2 where the syslog_pipe contains events, the osqueryd is able to successfully open the pipe, but the table `syslog_events` contains nothing.

**Comment by theopolis** [comment] 2020-06-29 03:17
Looking into this, I think a combination of the two suggested approaches is easiest.

The implementation can continue to use `::in_avail` but when there is `0`, a small loop-read-1 can be tried until a delimiter is encountered. This reads a single byte from the available stream and returns the context (slow) but is very easy to implement.

This allows the implementation to remain non-blocking such that we never encounter the teardown issue mentioned.

**Closed** 2020-12-22 12:56 UTC
