### ISSUE TITLE
FIM Configuration refresh interval doesn't setup watcher for new files, so inotify CREATED file event doesn't gets reported 

### ISSUE THREAD

**Issue by erdarun** [osquery/osquery#4259] opened 2018-04-04 08:02 UTC
FIM Configuration designed to refresh only when there are changes in comparison to existing configurations.

Say during OSQuery startup config pull has files that are not created then inotify watchers will not be setup for those files initially. Later during config refresh interval files got created and available but inotify watchers will not be setup for those new files during config refresh since config hash comparison hasn't changed. It requires OSQuery to be restarted for watching new files everytime instead of having that implemented during config refresh interval.

My suggestion will be introducing "config-refresh-always" boolean flag for OSQuery. When this flag is enabled we should skip config hash check and setup watchers even for new files created during config refresh interval.

Because of existing OSQuery behaviour we can't report/catch inotify CREATED event for new files.

Please check and revert.

**Comment by muffins** [comment] 2018-04-05 14:40
Similar to your other FIM issue, can you give us more information regarding what platform you're running on, version of osquery, etc..

**Comment by erdarun** [comment] 2018-04-10 11:06
@muffins Running FIM on both RedHat Enterprise Linux Server 6.8, CentOS 7 & macOS Sierra 10.12.6. OSQuery version is "osquery-2.7.0-1.linux.x86_64.rpm"

**Comment by muffins** [comment] 2018-04-10 18:30
I haven’t verified there were any changes to FIM after 2.7.0, but can you try and reproduce with the latest stable cut, 2.11.2?

**Comment by muffins** [comment] 2018-04-23 03:04
@erdarin I mentioned in you’re other issue, have you had a chance to upgrade to 2.11.2 and reproduce the behavior?

**Comment by mike-myers-tob** [comment] 2021-04-02 21:38
>  existing OSQuery behaviour we can't report/catch inotify CREATED event for new files.

I agree this is a problem, but closing this issue as a duplicate of #3212

**Closed by mike-myers-tob** 2021-04-02 21:38 UTC
Labels: FIM, question, triage
