### ISSUE TITLE
The alf table in mac OS not showing anything in mac OS 15

### ISSUE THREAD

**Issue by dioptriman** [osquery/osquery#8447] opened 2024-10-18 02:51 UTC
# Bug report

### What operating system and version are you using?
Mac OS version 15.0.1, build 24A348, platform Darwin

### What version of osquery are you using?
Osquery version 5.13.1

### What steps did you take to reproduce the issue?
SELECT * FROM alf;

### What did you expect to see?
It should detect anything about the details of mac OS firewall 

### What did you see instead?
I see nothing returned when the steps are called.

**Comment by directionless** [comment] 2024-10-18 14:18
This is a duplicate of https://github.com/osquery/osquery/issues/8395 and was fixed by https://github.com/osquery/osquery/pull/8428 which will be part of the upcoming 5.14 release.

**Closed by directionless** 2024-10-18 14:18 UTC
