### ISSUE TITLE
hash.cpp build failed in VS2015

### ISSUE THREAD

**Issue by aalon2** [osquery/osquery#5295] opened 2018-11-13 09:42 UTC
### What operating system and version are you using?
windows 10
Visual studio 2015

### What version of osquery are you using?
Commit hash:	5188ce5288abe0e323b8e8bd364f452134a62d00

### What steps did you take to reproduce the issue?
bulit with make-win64-dev-env.bat
attempt do build afterward with make-win64-binaries.bat failed
attempt to build with VS2015 failed on hash.cpp

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		no operator "+" matches these operands	osquery_tables_integration_tests	\osquery\tests\integration\tables\hash.cpp	39

**Comment by packetzero** [comment] 2018-11-13 15:54
It's complaining about the following line, which shouldn't be a problem.  
`  const std::string query = "select * from hash where path = '" + path.native() + "'";`

Can you move/rename your build directory to build.old and run the make-win64-dev-env.bat (as Admin) and then make-win64-binaries.bat again?  The last change (5188ce5) had a change to CMakeLists, and well as an updated aws package dependency.  So definitely needed a clean dependencies... unfortunately, since it takes a while to rebuild.

**Comment by aalon2** [comment] 2018-11-13 20:52
thanks, It indeed solve it. but I'm still having errors on:

Error	C1083	Cannot open include file: 'benchmark/benchmark.h': No such file or directory	osquery_benchmarks	C:\Users\aalon2\Documents\os\osquery\osquery\main\benchmarks.cpp	11	

I saw this is already a known issue:
https://github.com/facebook/osquery/issues/4554

but the issue is already closed. I can anyway bypass it by just skip this project in the configuration manager. but you may be interesting to know about it

**Comment by mike-myers-tob** [comment] 2019-08-31 01:51
@Smjert we are only supporting VS 2017 now and the build steps have changed. Is this issue still valid or should it be closed?

**Comment by Smjert** [comment] 2019-08-31 10:07
VS 2015 is untested now, though I had the same issue with VS 2017 when updating our old master osql project.
In fact in this repository, the `path.native()` part has become `path.string()`.
Since hash.cpp doesn't explicitly include the headers of the libraries it uses (a thing that imho all code should do) and since in the past it has been solved with external changes, I wonder if it's due to a missing header.
The issue is not present now, but I'm not sure it has been corrected properly.

**Comment by Smjert** [comment] 2021-04-25 12:13
This has been fixed by https://github.com/osquery/osquery/commit/e8354cd9ca296e4c007fc92aecb8dad74a8b245b

**Closed by Smjert** 2021-04-25 12:13 UTC
Labels: Windows
