### ISSUE TITLE
osquery eating cpu [linux]

### ISSUE THREAD

**Issue by juju4** [osquery/osquery#5234] opened 2018-09-23 21:10 UTC
# Bug report

In some conditions still unidentified, osquery is eating one core/cpu. Still nice 10 but.
Observed in Centos7 environments (fim only config)
And Ubuntu 16.04 (fim and packs)

That may be related to https://github.com/facebook/osquery/issues/4191 or not but 4191 seems more windows focused

Looking for ideas to find root cause...

Workaround from trailofbits: limit resource consumption with cgroups
```
# systemctl set-property osqueryd.service CPUQuota=5% MemoryLimit=1G CPUShares=20
```
(use osqueryd.service, not osqueryd.slice)

### What operating system and version are you using?

Tested on Centos7 and ubuntu 16.04

### What version of osquery are you using?

```
# osqueryi --line "SELECT version from osquery_info;"
version = 3.2.6
```
from ppa for ubuntu (latest available, not 3.3.0?)
If I try to manually update on ubuntu
```
# wget https://pkg.osquery.io/deb/osquery_3.3.0_1.linux.amd64.deb
# dpkg -i osquery_3.3.0_1.linux.amd64.deb 
(Reading database ... 153837 files and directories currently installed.)
Preparing to unpack osquery_3.3.0_1.linux.amd64.deb ...
Unpacking osquery (3.3.0-1.linux) over (3.2.6-1.linux) ...
dpkg: error processing archive osquery_3.3.0_1.linux.amd64.deb (--install):
 unable to create '/etc/init.d/osqueryd.dpkg-new' (while processing './etc/init.d/osqueryd'): Permission denied
Processing triggers for systemd (229-4ubuntu21.4) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 osquery_3.3.0_1.linux.amd64.deb
```

``` osquery.conf
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "events_expiry": "3600",
    "verbose": "false",
    "worker_threads": "2",
    "enable_monitor": "true"
  },
  "schedule": {
    "system_info": {
      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
      "interval": 3600
    },
    "fim" : {
      "query": "select * from file_events;",
      "removed": false,
      "interval": 900
    },
    "process_events":{
      "query": "SELECT auid, cmdline, ctime, cwd, egid, euid, gid, parent, path, pid, time, uid FROM process_events WHERE path NOT IN ('/bin/date', '/bin/mktemp', '/usr/bin/dirname', '/usr/bin/head', '/bin/uname', '/bin/basename') and cmdline NOT LIKE '%_key%' AND cmdline NOT LIKE '%secret%';",
      "interval": 900
    },
    "socket_events":{
      "query": "SELECT action, auid, family, local_address, local_port, path, pid, remote_address, remote_port, success, time FROM socket_events WHERE success=1 AND path NOT IN ('/usr/bin/hostname') AND remote_address NOT IN ('127.0.0.1', '169.254.169.254', '', '0000:0000:0000:0000:0000:0000:0000:0001', '::1', '0000:0000:0000:0000:0000:ffff:7f00:0001', 'unknown', '0.0.0.0', '0000:0000:0000:0000:0000:0000:0000:0000');",
      "interval": 900
    }
  },
  "file_paths": {
    "homes_sshdir": [
      "/root/.ssh/%%",
      "/home/%/.ssh/%%"
    ],
    "etc": [
      "/etc/%%"
    ],
    "bin": [
      "/bin/%%",
      "/sbin/%%",
      "/usr/bin/%%", 
      "/usr/sbin/%%",
      "/usr/local/bin/%%",
      "/usr/local/sbin/%%",
      "/opt/bin/%%", 
      "/opt/sbin/%%" 
    ],
    "tmptest": [
      "/tmp/test/%%"
    ],
    "webroot": [
      "/var/www/%%"
    ]
  },
  "exclude_paths": {
    "tmptest": [
      "/tmp/test/too_many_events/%%"
     ]
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },
  "packs": {
    "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
    "incident-response": "/usr/share/osquery/packs/incident-response.conf",
    "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
    "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
    "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf",
    "osquery-custom-pack": "/usr/share/osquery/packs/osquery-custom-pack.conf",
    "osquery-snapshots-pack": "/usr/share/osquery/packs/osquery-snapshots-pack.conf"
  }
}
```

```osquery.flags
--pidfile=/var/run/osqueryd.pid
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
```

### What steps did you take to reproduce the issue?

I did the following tests
a. reference: no osqueryd running
b. osqueryd packs+fim, do some stress I/O (fallocate 100M, split -b 100) in a directory not watched
c. osqueryd packs+fim, do some stress I/O (fallocate 100M, split -b 100) in a directory parent watched but stress directories excluded in exclude_path and 'select * from file_events'
d. osqueryd packs+fim, do some stress I/O (fallocate 100M, split -b 100) in a directory parent watched but stress directories excluded in exclude_path only
e. osqueryd packs+fim, no load
g. osqueryd packs+fim, stress cpu (stress-ng -a 0)

### What did you expect to see?

On normal system, typical osquery cpu is less than 1%
for tests b-d, osquery has a slight increase but when fim directory watched, more auditd and systemd-journal which are loaded (and split of course).
That seems consistent with switch to auditd (https://github.com/facebook/osquery/pull/3492) but not reflected in documentation which still have inotify base (https://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/)

from sysdig trace record, osquery seems to do mostly futex and poll syscalls, meaning waiting I guess (on I/O?). I/O on /var/log/audit, loaded target /tmp/test/too_many_events/. globally, first syscall is switch.

Tried some flamegraph record (svg)
(d) https://share.riseup.net/#bTirWGNGiCI-vV8QF1Rmwg (download to interact/select osqueryd: mainly __start call)

### What did you see instead?

On affected system, 1 core cpu is fully loaded when osqueryd active.
That barely changes with tests b-d as split seems not multithreaded. no auditd, systemd-journal activity.
For g test, stress-ng take over cpu from priority.
sysdig trace record is similar from a osqueryd syscall perspective, mostly futex and poll. I/O mostly on /var/osquery/osquery.db and /tmp/test/too_many_events/ when doing I/O stress

Flamegraph (svg)
(d) https://share.riseup.net/#bTirWGNGiCI-vV8QF1Rmwg ([osqueryd], irq_entries_start, only noticeable call above is _memcmp_sse4_1)

**Comment by rustybrooks** [comment] 2018-10-01 17:30
I have had some osquery users in our enterprise report very high CPU loads - 100-150%.  We use the watchdog stuff, so this causes osqueryd to be repeatedly killed.  I thought possibly that it might be just this bad at startup, so I added --watchdog_delay=120, and it stayed at 100% for the whole 2 minutes.

The only thing of potential interest in the logs is that it complains about overflowing socket events every 10s or so

```
W1001 17:15:06.160025 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:15:13.100443 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:15:20.629142 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:15:31.357046 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:15:41.861518 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:15:52.231429 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:16:04.358956 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:16:15.814586 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:16:26.269940 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
W1001 17:16:36.608635 13615 events.cpp:313] Expiring events for subscriber: socket_events (overflowed limit 50000)
```

**Comment by clong** [comment] 2018-10-01 22:53
You say (fim only config), but you have full system auditing enabled with:
```
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
```

What is likely happening here is that there is a process on this host generating a bunch of execve, connect, or bind syscalls that are overwhelming osquery because it can't parse them fast enough. 

The easiest way to triage this is to: 
1. Stop osquery entirely 
2. Start the auditd service 
3. Add the same audit rules that osquery uses:
```
auditctl -a exit,always -S execve
auditctl -a exit,always -S bind
auditctl -a exit,always -S connect
```
4. Let the system run for a few minutes
5. Stop the auditd service 
6. `for SYSCALL in connect bind execve; do echo "Report for $SYSCALL"; ausearch --syscall $SYSCALL --line-buffered --raw | aureport --executable --summary | head -15; done`

This will give you an overview of the processes generating the most events for each syscall. From there, you can create audit rules to filter out those events, or simply disable process and socket auditing all together.

**Comment by juju4** [comment] 2018-10-01 23:45
So, I managed to solve this on one system.  checking for others.

while checking strace, I got.
```
pread64(39, "\0)\307\1data.audit.user_events.00001"..., 3917, 2054096) = 3917
pread64(39, "\0)\315\1data.audit.user_events.00001"..., 3912, 2058013) = 3912
pread64(39, "\0)\301\1data.audit.user_events.00001"..., 3906, 2061925) = 3906
```
I compared audit.rules and they are not different between system with high cpu and normal ones but it's a non-empty config (~300 lines, mostly CIS & community inspired, part not covered by osquery). But one thing, on high cpu system, auditd daemon is not active in systemctl and fails to start (auditd.conf and audit.rules are same).
```
# auditd -f
[...]
type=DAEMON_START msg=audit(1538323564.306:505): auditd start, ver=2.4.5 format=raw kernel=4.4.0-134-generic auid=0 pid=3551 subj=unconfined  res=success
config_manager init complete
Error setting audit daemon pid (File exists)
type=DAEMON_ABORT msg=audit(1538323564.312:506): auditd error halt, auid=0 pid=3551 subj=unconfined  res=failed
Unable to set audit pid, exiting
The audit daemon is exiting.
Error setting audit daemon pid (Permission denied)
# ls -l /var/run/auditd.pid
ls: cannot access '/var/run/auditd.pid': No such file or directory
```
permissions were fine. no selinux/apparmor there.
rebooting system solved the issue for auditd and osquery on this system.

**Comment by muffins** [comment] 2018-10-22 17:05
@juju4 is this still an issue? This seems like it might be more of a problem with osquery configuration as opposed to a bug or issue in osquery itself? Let me know if we still need this open, thanks.

**Comment by juju4** [comment] 2018-10-22 22:10
I'm still trying to get a clear feedback in another environment but system is not accessible to me.
I think it's fine to close but if you have advice to help trace cpu/load issues, feel free to add :)
Thanks!

**Comment by juju4** [comment] 2018-10-27 15:17
Few hints I got
- seems one of observed folder has 600k active files I/O. in this case, I don't think there is much option outside of excluding it.
- system creating a lot of [/var]/tmp/osqueryd.<hostname>.invalid-user.log.<INFO|WARNING>.<TIMESTAMP>. more than usual. not sure cause of this.
- many memory limit or performance limit exceeded. does not seem to appear at same time than file_events overflow. if file_events overflow, I reduce fim interval. on limit, I suppose there is a very active folder that need to be excluded.
- observe behavior of osquery starting, eating cpu, restarted (most probably by watchdog) and looping like that. not sure if there is a settings to say to watchdog stop restarting after x fails in y time. not seen on https://osquery.readthedocs.io/en/stable/installation/cli-flags/#daemon-control-flags

**Comment by ReK2Fernandez** [comment] 2018-11-08 00:50
having this same issue with an alienvault agent install that uses osquery to pull data.

**Comment by packetzero** [comment] 2018-11-08 14:46
@ReK2Fernandez contact me directly or through AlienVault support so we can determine the cause and get you a workaround until this is fixed.

**Comment by ReK2Fernandez** [comment] 2018-11-09 21:04
@packetzero I tried telling someone there. did they give you my email?

**Comment by sc68cal** [comment] 2020-03-04 18:46
@juju4 I just encountered the same issue - where installing `osquery` made `auditd` unable to start, which was breaking our builds. Thanks for posting the information, you saved me a lot of aggravation.

**Comment by alessandrogario** [comment] 2020-03-04 19:08
Hello @sc68cal!

Auditd must always be disabled when osquery is running with audit support, because it takes ownership of the netlink. More details on how the machine should be configured can be found here: https://osquery.readthedocs.io/en/stable/deployment/process-auditing/#linux-process-auditing

I'm closing this issue as it is based on a very old osquery version that is no longer maintained. Feel free to open a new issue related to 4.x!

**Closed by alessandrogario** 2020-03-04 19:08 UTC
Labels: Linux, performance, question
